import { configureGoFixture } from './helpers/provider-config';
import { SELF } from 'cloudflare:test';
import { describe,it,expect,vi,afterEach } from 'vitest';
import { env,BASE } from './helpers/env';
import { seedUser,seedProject,authCookie } from './helpers/seed';
import { newId,nowIso } from '../src/core/db';
import { dispatchProjectProgression,projectFeedback } from '../src/services/project-progression';
import { applyProposal } from '../src/services/collaboration';
import { runCollaborationAiJob } from '../src/services/collaboration-ai';
await configureGoFixture();
const offline={...env,AGENT_WORKFLOW:{create:async()=>{throw new Error('offline workflow fixture');}}} as unknown as typeof env;
async function fixture(){const user=await seedUser(),projectId=await seedProject(user.userId);const req=async(path:string,method='GET',body?:unknown)=>{const r=await SELF.fetch(`${BASE}/api/v1/projects/${projectId}/collaboration${path}`,{method,headers:{cookie:authCookie(user.token),'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,json:await r.json() as any};};return {user,projectId,req};}
async function event(projectId:string,actor='user',recent=false){await env.DB.prepare(`INSERT INTO events(id,project_id,actor_type,actor_id,type,entity_type,entity_id,dedup_key,payload_json,occurred_at) VALUES(?1,?2,?3,'test','task.updated','task','test',?1,'{}',?4)`).bind(newId(),projectId,actor,new Date(Date.now()-(recent?0:60000)).toISOString()).run();}
afterEach(()=>vi.unstubAllGlobals());
describe('autonomous progress and independent owner correction',()=>{
 it('debounces user events, ignores AI events and persists exactly one progression job',async()=>{const f=await fixture();await env.DB.prepare('UPDATE projects SET ai_collaboration_enabled=1 WHERE id=?1').bind(f.projectId).run();await event(f.projectId,'ai');await dispatchProjectProgression(offline);expect(await env.DB.prepare('SELECT 1 FROM project_progression WHERE project_id=?1').bind(f.projectId).first()).toBeNull();await event(f.projectId,'user',true);await dispatchProjectProgression(offline);expect(await env.DB.prepare('SELECT 1 FROM project_progression WHERE project_id=?1').bind(f.projectId).first()).toBeNull();await env.DB.prepare('UPDATE events SET occurred_at=?2 WHERE project_id=?1').bind(f.projectId,new Date(Date.now()-60000).toISOString()).run();await dispatchProjectProgression(offline);await dispatchProjectProgression(offline);const jobs=await env.DB.prepare('SELECT input_json FROM jobs WHERE project_id=?1').bind(f.projectId).all<{input_json:string}>();expect(jobs.results).toHaveLength(1);expect(JSON.parse(jobs.results[0]!.input_json).progression).toBe(true);});
 it('no-change progress completes without inventing more tasks',async()=>{const f=await fixture();await env.DB.prepare('UPDATE projects SET ai_collaboration_enabled=1 WHERE id=?1').bind(f.projectId).run();await event(f.projectId);await dispatchProjectProgression(offline);const job=await env.DB.prepare('SELECT id FROM jobs WHERE project_id=?1').bind(f.projectId).first<{id:string}>();vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({tasks:[],updates:[]})}}],usage:{prompt_tokens:10,completion_tokens:10}}),{headers:{'content-type':'application/json'}})));await runCollaborationAiJob(offline,job!.id);const result=await env.DB.prepare('SELECT status,result_json FROM jobs WHERE id=?1').bind(job!.id).first<{status:string;result_json:string}>();expect(result?.status).toBe('succeeded');expect(JSON.parse(result!.result_json).noChange).toBe(true);await dispatchProjectProgression(offline);expect((await env.DB.prepare('SELECT COUNT(*) n FROM jobs WHERE project_id=?1').bind(f.projectId).first<{n:number}>())!.n).toBe(1);});
 it('owner revises accepted results and reopens while AI is disabled',async()=>{const f=await fixture();const task=(await f.req('/tasks','POST',{title:'成果',criteria:'原标准'})).json.data;await f.req(`/tasks/${task.taskId}/claim`,'POST',{expectedRevision:1});const submission=(await f.req(`/tasks/${task.taskId}/submissions`,'POST',{expectedRevision:2,body:'原成果'})).json.data;expect((await f.req(`/submissions/${submission.submissionId}/decide`,'POST',{expectedRevision:1,decision:'accept',feedback:'通过'})).status).toBe(200);expect((await f.req(`/tasks/${task.taskId}`,'PATCH',{expectedRevision:4,title:'修正版'})).status).toBe(200);expect((await f.req(`/submissions/${submission.submissionId}/decide`,'POST',{expectedRevision:2,decision:'improve',feedback:'管理员复核需要补充'})).status).toBe(200);const reopened=await f.req(`/tasks/${task.taskId}/reopen`,'POST',{expectedRevision:6,feedback:'重新工作'});expect(reopened.status).toBe(200);expect(reopened.json.data.lifecycleState).toBe('rework');const unassigned=await f.req(`/tasks/${task.taskId}/assign`,'POST',{expectedRevision:7,assigneeId:null,reason:'重新分工'});expect(unassigned.status).toBe(200);expect(unassigned.json.data.assigneeId).toBeNull();});
 it('editing a pending proposal does not trigger a replacement before owner applies it',async()=>{const f=await fixture();await env.DB.prepare('UPDATE projects SET ai_collaboration_enabled=1 WHERE id=?1').bind(f.projectId).run();await env.DB.prepare(`INSERT INTO events(id,project_id,actor_type,actor_id,type,entity_type,entity_id,dedup_key,payload_json,occurred_at) VALUES(?1,?2,'user',?3,'collaboration.proposal_revised','collaboration',?1,?1,'{}',?4)`).bind(newId(),f.projectId,f.user.userId,new Date(Date.now()-60000).toISOString()).run();await dispatchProjectProgression(offline);expect(await env.DB.prepare('SELECT 1 FROM project_progression WHERE project_id=?1').bind(f.projectId).first()).toBeNull();});
 it('admin feedback persists without enabling AI or blocking manual work',async()=>{const f=await fixture();const result=await f.req('/feedback','POST',{feedback:'下一阶段先补充实验',requestAiRedo:true});expect(result.status).toBe(200);expect(await projectFeedback(env,f.projectId)).toHaveLength(1);expect((await f.req('/settings')).json.data.aiCollaborationEnabled).toBe(false);});
 it('partial application excludes entries, revisions remain immutable and settings do not gate owner',async()=>{const f=await fixture(),jobId=newId(),proposalId=newId(),now=nowIso();await env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,attempts,created_at,updated_at) VALUES(?1,?2,'agent_run','succeeded','{}',0,?3,?3)").bind(jobId,f.projectId,now).run();await env.DB.prepare("INSERT INTO collaboration_proposals(id,project_id,kind,job_id,payload_json,settings_revision,created_at,updated_at) VALUES(?1,?2,'decompose',?3,?4,1,?5,?5)").bind(proposalId,f.projectId,jobId,JSON.stringify({tasks:[{key:'a',title:'A',detail:'',criteria:'A works',effortHours:1},{key:'b',title:'B',detail:'',criteria:'B works',effortHours:1}]}),now).run();await f.req('/settings','PATCH',{expectedRevision:1,assignmentMode:'automatic'});const result=await applyProposal(env,f.projectId,proposalId,1,f.user.userId,false,undefined,{selectedTaskKeys:['a']});expect(result.taskIds).toHaveLength(1);const task=(await f.req('/tasks')).json.data.items[0];const revision=await f.req(`/proposals/${proposalId}`,'PATCH',{expectedRevision:2,payload:{tasks:[],updates:[{taskId:task.taskId,title:'A 修正',detail:'',criteria:'new',effortHours:1,expectedRevision:1}]},reason:'管理员修正'});expect(revision.status).toBe(200);await applyProposal(env,f.projectId,proposalId,3,f.user.userId);expect((await f.req('/tasks')).json.data.items).toHaveLength(1);expect((await env.DB.prepare('SELECT COUNT(*) n FROM collaboration_proposal_revisions WHERE proposal_id=?1').bind(proposalId).first<{n:number}>())!.n).toBe(1);});
});
