import { SELF } from 'cloudflare:test';
import { expect, it } from 'vitest';
import { env, BASE } from './helpers/env';
import { authCookie, seedProject, seedUser } from './helpers/seed';
import { newId, nowIso } from '../src/core/db';
import { createFileInit } from '../src/services/files';
import { fileContributors } from '../src/services/file-contributors';
it('validates contributor membership, snapshots names, inherits attribution and keeps old files unmarked', async () => {
  const owner = await seedUser('owner@example.com', 'Owner');
  const other = await seedUser('member@example.com', 'Contributor');
  const outside = await seedUser('outside@example.com');
  const projectId = await seedProject(owner.userId);
  await env.DB.prepare("INSERT INTO project_members(id,project_id,user_id,role,joined_at) VALUES (?1,?2,?3,'member',?4)").bind(newId(),projectId,other.userId,nowIso()).run();
  const init = await createFileInit(env,{projectId,uploaderUserId:owner.userId,fileName:'file.pdf',contributorIds:[owner.userId,other.userId,other.userId]});
  expect(await fileContributors(env,projectId,init.fileId)).toHaveLength(2);
  const defaultFile = await createFileInit(env,{projectId,uploaderUserId:owner.userId,fileName:'default.txt'});
  expect(await fileContributors(env,projectId,defaultFile.fileId)).toEqual([{userId:owner.userId,displayName:'Owner'}]);
  await expect(createFileInit(env,{projectId,uploaderUserId:owner.userId,fileName:'invalid.pdf',contributorIds:[outside.userId]})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  await expect(createFileInit(env,{projectId,uploaderUserId:owner.userId,fileName:'invalid.pdf',contributorIds:[]})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  await env.DB.prepare('DELETE FROM project_members WHERE project_id=?1 AND user_id=?2').bind(projectId,other.userId).run();
  await env.DB.prepare('UPDATE users SET display_name=?2 WHERE id=?1').bind(other.userId,'Renamed').run();
  const derivative = await createFileInit(env,{projectId,uploaderUserId:owner.userId,fileName:'page.png',derivedFromFileId:init.fileId});
  expect(await fileContributors(env,projectId,derivative.fileId)).toEqual(await fileContributors(env,projectId,init.fileId));
  expect((await fileContributors(env,projectId,init.fileId)).find(person=>person.userId===other.userId)?.displayName).toBe('Contributor');
  const foreignProject = await seedProject(outside.userId);
  await expect(createFileInit(env,{projectId:foreignProject,uploaderUserId:outside.userId,fileName:'page.png',derivedFromFileId:init.fileId})).rejects.toMatchObject({code:'VALIDATION_FAILED'});
  await env.DB.prepare('DELETE FROM file_contributors WHERE file_id=?1').bind(defaultFile.fileId).run();
  expect(await fileContributors(env,projectId,defaultFile.fileId)).toEqual([]);
  const list=await SELF.fetch(`${BASE}/api/v1/projects/${projectId}/files`,{headers:{cookie:authCookie(owner.token)}});
  expect(list.status).toBe(200);
  const data=await list.json() as {data:{items:Array<{fileId:string;contributors:unknown[];uploaderUserId:string}>}};
  expect(data.data.items.find(file=>file.fileId===init.fileId)?.contributors).toHaveLength(2);
  expect(data.data.items.find(file=>file.fileId===init.fileId)?.uploaderUserId).toBe(owner.userId);
});

it('restricts material attachment and document writes to creators or resource managers', async () => {
 const owner=await seedUser(), reader=await seedUser('reader@example.com'); const projectId=await seedProject(owner.userId);
 await env.DB.prepare("INSERT INTO project_members(id,project_id,user_id,role,joined_at) VALUES (?1,?2,?3,'member',?4)").bind(newId(),projectId,reader.userId,nowIso()).run();
 const create=await SELF.fetch(`${BASE}/api/v1/projects/${projectId}/materials`,{method:'POST',headers:{cookie:authCookie(owner.token),'content-type':'application/json'},body:JSON.stringify({title:'Material',kind:'report'})});
 expect(create.status).toBe(201);
 const material=(await create.json() as {data:{materialId:string;revision:number}}).data;
 const url=`${BASE}/api/v1/projects/${projectId}/materials/${material.materialId}`;
 const read=await SELF.fetch(url,{headers:{cookie:authCookie(reader.token)}});
 expect((await read.json() as {data:{canEdit:boolean}}).data.canEdit).toBe(false);
 const save=()=>SELF.fetch(url,{method:'PUT',headers:{cookie:authCookie(reader.token),'content-type':'application/json'},body:JSON.stringify({expectedRevision:material.revision,doc:{type:'doc',content:[]},attachmentIds:[]})});
 expect((await save()).status).toBe(403);
 await env.DB.prepare('UPDATE project_members SET permissions_json=?3 WHERE project_id=?1 AND user_id=?2').bind(projectId,reader.userId,JSON.stringify({resourceManage:true})).run();
 expect((await save()).status).toBe(201);
});
