import { SELF } from 'cloudflare:test';
import { describe, expect, it } from 'vitest';
import { env, BASE } from './helpers/env';
import { authCookie, seedProject, seedUser } from './helpers/seed';
import { newId,nowIso } from '../src/core/db';
import { assertCanRegenerate } from '../src/services/task-planning-policy';
import { applyProposal } from '../src/services/collaboration';
async function fixture(){const owner=await seedUser(),member=await seedUser(),recipient=await seedUser(),projectId=await seedProject(owner.userId);await env.DB.prepare("INSERT INTO project_members(id,project_id,user_id,role,joined_at,permissions_json) VALUES(?1,?2,?3,'member',?4,?5)").bind(newId(),projectId,member.userId,nowIso(),JSON.stringify({teamManage:true})).run();const req=(token:string,tail:string,method='GET',body?:unknown)=>SELF.fetch(`${BASE}/api/v1/projects/${projectId}${tail}`,{method,headers:{cookie:authCookie(token),'content-type':'application/json','idempotency-key':newId()},...(body?{body:JSON.stringify(body)}:{})});return {owner,member,recipient,projectId,req};}
async function addMember(projectId:string,userId:string,permissions?:Record<string,boolean>){await env.DB.prepare(permissions?"INSERT INTO project_members(id,project_id,user_id,role,joined_at,permissions_json) VALUES(?1,?2,?3,'member',?4,?5)":"INSERT INTO project_members(id,project_id,user_id,role,joined_at) VALUES(?1,?2,?3,'member',?4)").bind(...(permissions?[newId(),projectId,userId,nowIso(),JSON.stringify(permissions)]:[newId(),projectId,userId,nowIso()] as unknown[])).run();}
async function task(projectId:string,owner:string){const id=newId(),now=nowIso();await env.DB.prepare("INSERT INTO tasks(id,project_id,title,status,lifecycle_state,criteria,created_by,created_at,updated_at) VALUES(?1,?2,'原任务','todo','open','可验收',?3,?4,?4)").bind(id,projectId,owner,now).run();return id;}
async function proposal(projectId:string,owner:string,action='regenerate'){const id=newId(),job=newId(),now=nowIso();await env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,created_at,updated_at) VALUES(?1,?2,'agent_run','succeeded','{}',?3,?3)").bind(job,projectId,now).run();await env.DB.prepare("INSERT INTO collaboration_proposals(id,project_id,kind,job_id,payload_json,settings_revision,status,revision,created_at,updated_at) VALUES(?1,?2,'decompose',?3,?4,1,'pending',1,?5,?5)").bind(id,projectId,job,JSON.stringify({planningAction:action,tasks:[{title:'新任务',detail:'说明',criteria:'验收',effortHours:1}]}),now).run();return id;}
describe('administrator approvals and immutable task start',()=>{
 it('teamManage members invite directly; members without it only request approval',async()=>{const f=await fixture();
  // teamManage=true 的协作管理员可直接创建邀请码与用户名邀请，不再需要历史 'grant'。
  expect((await f.req(f.member.token,'/invitations','POST',{})).status).toBe(201);
  expect((await f.req(f.member.token,'/username-invitations','POST',{username:`fixture-${f.recipient.userId}`})).status).toBe(201);
  // 无 teamManage 的普通成员只能提交申请，且不能自行审批。
  const plain=await seedUser(),other=await seedUser();await addMember(f.projectId,plain.userId);
  expect((await f.req(plain.token,'/invitations','POST',{})).status).toBe(403);
  expect((await f.req(plain.token,'/username-invitations','POST',{username:`fixture-${other.userId}`})).status).toBe(403);
  const r=await f.req(plain.token,'/invitation-requests','POST',{username:`fixture-${other.userId}`});expect(r.status).toBe(201);
  const {data}=await r.json() as {data:{id:string;revision:number}};
  expect(await env.DB.prepare('SELECT id FROM project_username_invitations WHERE project_id=?1 AND recipient_id=?2').bind(f.projectId,other.userId).first()).toBeNull();
  expect((await f.req(plain.token,`/invitation-requests/${data.id}/decide`,'POST',{expectedRevision:1,action:'approve'})).status).toBe(403);
  expect((await f.req(f.member.token,`/invitation-requests/${data.id}/decide`,'POST',{expectedRevision:1,action:'approve'})).status).toBe(200);
  expect(await env.DB.prepare('SELECT id FROM project_username_invitations WHERE project_id=?1 AND recipient_id=?2').bind(f.projectId,other.userId).first()).not.toBeNull();
  expect((await f.req(f.member.token,`/invitation-requests/${data.id}/decide`,'POST',{expectedRevision:1,action:'reject'})).status).toBe(409);});
 it('claim then unassign never reopens regeneration permission',async()=>{const f=await fixture(),id=await task(f.projectId,f.owner.userId);await assertCanRegenerate(env,f.projectId);expect((await f.req(f.member.token,`/collaboration/tasks/${id}/claim`,'POST',{expectedRevision:1})).status).toBe(200);await env.DB.prepare("UPDATE tasks SET assignee_id=NULL,status='todo',lifecycle_state='open' WHERE id=?1").bind(id).run();await expect(assertCanRegenerate(env,f.projectId)).rejects.toThrow('曾被认领');expect((await f.req(f.owner.token,'/collaboration/decompose','POST',{brief:'重新生成'})).status).toBe(409);});
 it('regeneration archives old tasks, retains detail history and replaces active graph',async()=>{const f=await fixture(),old=await task(f.projectId,f.owner.userId),id=await proposal(f.projectId,f.owner.userId);await expect(applyProposal(env,f.projectId,id,1,f.member.userId)).rejects.toThrow('权限');const result=await applyProposal(env,f.projectId,id,1,f.owner.userId);expect(result.taskIds).toHaveLength(1);expect((await env.DB.prepare('SELECT archived_at FROM tasks WHERE id=?1').bind(old).first<{archived_at:string}>())?.archived_at).toBeTruthy();const r=await f.req(f.owner.token,'/tasks');const list=await r.json() as {data:{items:Array<{taskId:string}>}};expect(list.data.items.map(t=>t.taskId)).toEqual(result.taskIds);expect((await f.req(f.owner.token,`/tasks/${old}`)).status).toBe(200);});
 it('task claims after generation block apply; adjustments never auto-apply',async()=>{const f=await fixture(),old=await task(f.projectId,f.owner.userId),id=await proposal(f.projectId,f.owner.userId);await f.req(f.member.token,`/collaboration/tasks/${old}/claim`,'POST',{expectedRevision:1});await expect(applyProposal(env,f.projectId,id,1,f.owner.userId)).rejects.toThrow('曾被认领');const adjust=await proposal(f.projectId,f.owner.userId,'adjust');await expect(applyProposal(env,f.projectId,adjust,1,f.owner.userId,true)).rejects.toThrow('明确确认');await applyProposal(env,f.projectId,adjust,1,f.owner.userId);expect((await env.DB.prepare('SELECT archived_at FROM tasks WHERE id=?1').bind(old).first<{archived_at:null}>())?.archived_at).toBeNull();});
});
