import { afterEach,describe,it,expect,vi } from 'vitest';
import { env } from './helpers/env';
import { seedUser,seedProject } from './helpers/seed';
import { configureGoFixture } from './helpers/provider-config';
import { loadAiConfig } from '../src/ai/config';
import { newId,nowIso } from '../src/core/db';
import { projectToolConversation } from '../src/services/project-ai-tools';
import { saveStandard } from '../src/services/project-simplification';
import { applyProposal,reviseProposal } from '../src/services/collaboration';
import { reserveAiSlot } from '../src/services/ai-reservations';
import { InvestigationContinuation,loadInvestigation } from '../src/services/project-investigation';
afterEach(()=>vi.unstubAllGlobals());
async function fixture(){await configureGoFixture();const owner=await seedUser(),projectId=await seedProject(owner.userId),config=(await loadAiConfig(env.DB))!;return {owner,projectId,params:{context:{projectId,userId:owner.userId},config:config.config.textEconomy,configVersionId:config.id,messages:[{role:'user' as const,content:'调查项目'}],promptVersion:'standard-conversation-guard'}};}
async function save(f:Awaited<ReturnType<typeof fixture>>,title:string){return saveStandard(env,f.projectId,f.owner.userId,{title,requirements:[{title,detail:''}],weights:[]});}
function toolResponse(){return Response.json({choices:[{finish_reason:'tool_calls',message:{tool_calls:[{id:'tasks',type:'function',function:{name:'list_tasks',arguments:'{}'}}]}}],usage:{prompt_tokens:10,completion_tokens:5}});}
describe('conversation effective standards snapshot',()=>{
 it('stops before any additional model dispatch after initial context standard changes',async()=>{const f=await fixture();await save(f,'初始标准');const fetch=vi.fn(async()=>{await save(f,'更新标准');return toolResponse();});vi.stubGlobal('fetch',fetch);await expect(projectToolConversation(env,f.params)).rejects.toThrow('标准已更新');expect(fetch).toHaveBeenCalledOnce();expect((await env.DB.prepare('SELECT COUNT(*) n FROM ai_tool_calls WHERE project_id=?1').bind(f.projectId).first<{n:number}>())!.n).toBe(0);});
 it('rejects a late final result with empty references when a first standard was saved during the call',async()=>{const f=await fixture(),fetch=vi.fn(async()=>{await save(f,'首次标准');return Response.json({choices:[{finish_reason:'stop',message:{content:'{"summary":"旧上下文结论","referenceIds":[],"decisionReferences":[]}'}}],usage:{prompt_tokens:10,completion_tokens:5}});});vi.stubGlobal('fetch',fetch);await expect(projectToolConversation(env,f.params)).rejects.toThrow('标准已更新');expect(fetch).toHaveBeenCalledOnce();});
 it('preserves null standard in checkpoints and refuses adopting a new standard when resuming paid output',async()=>{const f=await fixture(),jobId=newId();await reserveAiSlot(env,{projectId:f.projectId,jobId,purpose:'review_run',maxCalls:24});await env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,created_at,updated_at) VALUES(?1,?2,'review_run','running','{}',?3,?3)").bind(jobId,f.projectId,nowIso()).run();const params={...f.params,context:{...f.params.context,jobId}},fetch=vi.fn(async()=>toolResponse());vi.stubGlobal('fetch',fetch);await expect(projectToolConversation({...env,AI_EXECUTION_SLICE:true},params)).rejects.toBeInstanceOf(InvestigationContinuation);expect((await loadInvestigation(env,jobId+'-'+params.promptVersion))?.effectiveStandardsVersionId).toBeNull();await save(f,'暂停期间新标准');await expect(projectToolConversation({...env,AI_EXECUTION_SLICE:true},params)).rejects.toThrow('标准已更新');expect(fetch).toHaveBeenCalledOnce();});
 it('blocks applying pending proposals after standard changes even with no cited references',async()=>{const f=await fixture(),id=newId(),jobId=newId(),now=nowIso(),payload={effectiveStandardsVersionId:null,references:[],tasks:[{key:'t1',title:'旧上下文任务',detail:'',criteria:'可核验',effortHours:1}]};await env.DB.batch([env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,created_at,updated_at) VALUES(?1,?2,'agent_run','running','{}',?3,?3)").bind(jobId,f.projectId,now),env.DB.prepare("INSERT INTO collaboration_proposals(id,project_id,kind,job_id,payload_json,settings_revision,created_at,updated_at) VALUES(?1,?2,'decompose',?3,?4,1,?5,?5)").bind(id,f.projectId,jobId,JSON.stringify(payload),now)]);await save(f,'生效标准');await expect(applyProposal(env,f.projectId,id,1,f.owner.userId)).rejects.toThrow();expect((await env.DB.prepare('SELECT COUNT(*) n FROM tasks WHERE project_id=?1').bind(f.projectId).first<{n:number}>())!.n).toBe(0);expect((await env.DB.prepare('SELECT status FROM collaboration_proposals WHERE id=?1').bind(id).first<{status:string}>())!.status).toBe('pending');});
 it('preserves server-captured standard metadata across manual revisions',async()=>{const f=await fixture(),standard=await save(f,'当前标准'),id=newId(),jobId=newId(),now=nowIso(),payload={effectiveStandardsVersionId:standard.standardsVersionId,references:[],tasks:[{key:'t1',title:'原任务',detail:'',criteria:'可核验',effortHours:1}]};await env.DB.batch([env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,created_at,updated_at) VALUES(?1,?2,'agent_run','running','{}',?3,?3)").bind(jobId,f.projectId,now),env.DB.prepare("INSERT INTO collaboration_proposals(id,project_id,kind,job_id,payload_json,settings_revision,created_at,updated_at) VALUES(?1,?2,'decompose',?3,?4,1,?5,?5)").bind(id,f.projectId,jobId,JSON.stringify(payload),now)]);const revised=await reviseProposal(env,f.projectId,id,1,{tasks:[{...payload.tasks[0],title:'人工修订'}],effectiveStandardsVersionId:newId()},'修正文案',f.owner.userId);expect(JSON.parse(revised.payload_json).effectiveStandardsVersionId).toBe(standard.standardsVersionId);await save(f,'后续标准');await expect(applyProposal(env,f.projectId,id,revised.revision,f.owner.userId)).rejects.toThrow();});

});
