import { afterEach, describe, expect, it, vi } from 'vitest';
import { env } from './helpers/env';
import { seedProject, seedUser } from './helpers/seed';
import { loadAiConfig, resolveAiConfig } from '../src/ai/config';
import { seal } from '../src/ai/secrets';
import { GeminiMediaClient, validateMediaModel, mediaCost } from '../src/ai/gemini-media';
import { newId, nowIso } from '../src/core/db';
import { uploadLimit, validateUploadBytes } from '../src/services/files';
import { runMediaJob, cleanupMediaFiles } from '../src/services/media-summary';
import { getJob } from '../src/services/jobs';
import { commitDraft, draftView, getDraft, prepareDraftPreviewAttempt } from '../src/services/creation-drafts';
import { runParseJob } from '../src/services/parse';
import { configureGoFixture } from './helpers/provider-config';

afterEach(()=>vi.unstubAllGlobals());
const output={title:'录像摘要',summary:'展示了试验过程',keyPoints:['试验结果'],conclusions:['成功'],actionItems:[],timestamps:[{seconds:2,description:'试验开始'}],caveats:[],complete:true,durationSeconds:30};
async function modelFixture(){const config=(await loadAiConfig(env.DB))!;const model={...config.config.textEconomy,provider:'openai-compatible',providerPreset:'gemini' as const,model:'gemini-2.5-flash',apiUrl:'https://generativelanguage.googleapis.com',apiKeyEncrypted:await seal('fixture-media-key',env.AUTH_SECRET),mediaInputPricePerMTokens:{audio:2,video:3,text:1},pricePerMTokens:[1,2] as [number,number]};config.config.mediaUnderstanding=model;await env.DB.prepare('UPDATE ai_config_versions SET config_json=?2,enabled=1 WHERE id=?1').bind(config.id,JSON.stringify(config.config)).run();return {config,model};}
async function sourceFixture(){const owner=await seedUser(),projectId=await seedProject(owner.userId),fileId=newId(),sourceId=newId(),versionId=newId(),jobId=newId(),now=nowIso();const {config}=await modelFixture();await env.FILES.put('fixture-media/'+fileId,new Uint8Array([0,0,0,16,102,116,121,112]));await env.DB.batch([
env.DB.prepare("INSERT INTO files(id,project_id,uploader_user_id,r2_key,ext,mime_detected,size_bytes,status,created_at) VALUES(?1,?2,?3,?4,'.mp4','video/mp4',8,'available',?5)").bind(fileId,projectId,owner.userId,'fixture-media/'+fileId,now),
env.DB.prepare("INSERT INTO sources(id,project_id,kind,title,current_version_id,created_by,created_at,updated_at) VALUES(?1,?2,'file','录制',?3,?4,?5,?5)").bind(sourceId,projectId,versionId,owner.userId,now),
env.DB.prepare("INSERT INTO source_versions(id,source_id,project_id,revision,origin,file_id,status,created_at) VALUES(?1,?2,?3,1,'file',?4,'pending',?5)").bind(versionId,sourceId,projectId,fileId,now),
env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,attempts,created_at,updated_at) VALUES(?1,?2,'parse_source','running',?3,0,?4,?4)").bind(jobId,projectId,JSON.stringify({sourceVersionId:versionId,sourceLifecycleVersion:1,configVersionId:config.id,phase:'extract'}),now),
]);return {projectId,fileId,sourceId,versionId,jobId};}
function mockProvider(options:{duration?:number;truncate?:boolean;complete?:boolean;cleanupFail?:boolean;generateError?:boolean;afterGenerate?:()=>Promise<void>}={}){
return vi.fn(async(url:RequestInfo|URL,init?:RequestInit)=>{
 const value=String(url);expect(new Headers(init?.headers).get('x-goog-api-key')).toBe('fixture-media-key');
 if(init?.method==='DELETE'){if(options.cleanupFail)return new Response('',{status:500});return new Response('{}');}
 if(value.endsWith('/upload/v1beta/files'))return new Response('{}',{headers:{'x-goog-upload-url':'https://generativelanguage.googleapis.com/upload/v1beta/files?upload_id=fixture'}});
 if(value.includes('upload_id=')){expect(init?.body).toBeInstanceOf(ReadableStream);return Response.json({file:{name:'files/fixture',uri:'https://generativelanguage.googleapis.com/v1beta/files/fixture',state:'ACTIVE'}});}
 if(value.includes(':generateContent')){if(options.generateError)throw new Error('connection reset');await options.afterGenerate?.();const body=JSON.parse(String(init?.body));const start=Number.parseFloat(body.contents[0].parts[0].video_metadata?.start_offset??'0');return Response.json({candidates:[{finishReason:options.truncate?'MAX_TOKENS':'STOP',content:{parts:[{text:JSON.stringify({...output,complete:options.complete??true,timestamps:[{seconds:start+2,description:'事件'}]})}]}}],usageMetadata:{promptTokenCount:100, candidatesTokenCount:40,promptTokensDetails:[{modality:'VIDEO',tokenCount:80},{modality:'TEXT',tokenCount:20}]}});}
 return Response.json({name:'files/fixture',uri:'https://generativelanguage.googleapis.com/v1beta/files/fixture',state:'ACTIVE',videoMetadata:{videoDuration:(options.duration??30)+'s'}});
});}
async function draftFixture(){const owner=await seedUser(),draftId=newId(),fileId=newId(),jobId=newId(),now=nowIso(),{config}=await modelFixture();await env.FILES.put('draft-media/'+fileId,new Uint8Array([0,0,0,16,102,116,121,112]));await env.DB.batch([
env.DB.prepare("INSERT INTO project_creation_drafts(id,owner_id,revision,payload_json,project_id,created_at,updated_at) VALUES(?1,?2,1,?3,?4,?5,?5)").bind(draftId,owner.userId,JSON.stringify({name:'媒体草稿',description:'媒体介绍',aiCollaborationEnabled:false}),newId(),now),
env.DB.prepare("INSERT INTO creation_draft_files(id,draft_id,name,ext,r2_key,sha256,size_bytes,mime,text_error,created_at) VALUES(?1,?2,'录制.mp4','.mp4',?3,'fixture',8,'video/mp4','处理中',?4)").bind(fileId,draftId,'draft-media/'+fileId,now),
env.DB.prepare("INSERT INTO jobs(id,kind,status,input_json,attempts,created_by,created_at,updated_at) VALUES(?1,'agent_run','running',?2,0,?3,?4,?4)").bind(jobId,JSON.stringify({operation:'media.draft',draftId,fileId,configVersionId:config.id}),owner.userId,now),
]);return {owner,draftId,fileId,jobId};}
describe('Gemini media processing',()=>{
 it.each([['.mp3',[73,68,51],'audio/mpeg'],['.wav',[82,73,70,70,0,0,0,0,87,65,86,69],'audio/wav'],['.m4a',[0,0,0,16,102,116,121,112],'audio/mp4'],['.mp4',[0,0,0,16,102,116,121,112],'video/mp4'],['.webm',[26,69,223,163],'video/webm']] as const)('validates %s magic without an application file size limit',(ext,bytes,mime)=>{expect(validateUploadBytes(ext,new Uint8Array(bytes))).toBe(mime);expect(uploadLimit(ext)).toBeNull();expect(()=>validateUploadBytes(ext,new Uint8Array([1,2,3]))).toThrow();});
 it('removes application size limits while rejecting invalid media magic',()=>{expect(uploadLimit('.pdf')).toBeNull();expect(()=>validateUploadBytes('.mp4',new Uint8Array(50*1024*1024+1))).toThrow();});
 it('keeps independent media config in unified mode',async()=>{const {config,model}=await modelFixture();expect(resolveAiConfig({...config.config,routingMode:'unified',unified:config.config.review}).mediaUnderstanding).toBe(model);expect(()=>validateMediaModel({...model,apiUrl:'https://other.example'})).toThrow();});
 it('uploads streams, saves labelled summary and timestamp metadata, accounts usage, removes provider file',async()=>{const f=await sourceFixture(),request=mockProvider();vi.stubGlobal('fetch',request);expect(await runMediaJob(env,f.jobId,f.versionId)).toEqual({status:'succeeded'});const fragment=await env.DB.prepare('SELECT content FROM source_fragments WHERE source_version_id=?1').bind(f.versionId).first<{content:string}>();expect(fragment?.content).toContain('AI 摘要（非逐字原文）');const state=await env.DB.prepare('SELECT summary_json,cleanup_pending FROM media_processing WHERE job_id=?1').bind(f.jobId).first<{summary_json:string;cleanup_pending:number}>();expect(JSON.parse(state!.summary_json).timestamps).toHaveLength(1);expect(state?.cleanup_pending).toBe(0);expect(await env.DB.prepare('SELECT cost_status FROM media_calls WHERE job_id=?1').bind(f.jobId).first()).toEqual({cost_status:'known'});});
 it('splits long video into persisted 600 second windows',async()=>{const f=await sourceFixture(),request=mockProvider({duration:1300});vi.stubGlobal('fetch',request);await runMediaJob(env,f.jobId,f.versionId);const state=await env.DB.prepare('SELECT windows_json FROM media_processing WHERE job_id=?1').bind(f.jobId).first<{windows_json:string}>();expect(JSON.parse(state!.windows_json)).toHaveLength(3);expect(request.mock.calls.filter(([url])=>String(url).includes(':generateContent'))).toHaveLength(3);});
 it('marks truncation failure and never replays an ambiguous paid call',async()=>{const f=await sourceFixture(),request=mockProvider({truncate:true});vi.stubGlobal('fetch',request);expect(await runMediaJob(env,f.jobId,f.versionId)).toEqual({status:'failed'});await runMediaJob(env,f.jobId,f.versionId);expect(request.mock.calls.filter(([url])=>String(url).includes(':generateContent'))).toHaveLength(1);expect(await env.DB.prepare('SELECT status FROM usage_reservations WHERE job_id=?1').bind(f.jobId).first()).toEqual({status:'pending_reconcile'});});
 it('persists partial results without marking them complete',async()=>{const f=await sourceFixture();vi.stubGlobal('fetch',mockProvider({complete:false}));await runMediaJob(env,f.jobId,f.versionId);const state=await env.DB.prepare('SELECT stage,summary_json FROM media_processing WHERE job_id=?1').bind(f.jobId).first<{stage:string;summary_json:string}>();expect(state?.stage).toBe('failed');expect(JSON.parse(state!.summary_json).complete).toBe(false);expect(await env.DB.prepare('SELECT COUNT(*) n FROM source_fragments WHERE source_version_id=?1').bind(f.versionId).first()).toEqual({n:0});});
 it('does not apply results after cancellation and still cleans provider files',async()=>{const f=await sourceFixture(),request=mockProvider({afterGenerate:async()=>{await env.DB.prepare("UPDATE jobs SET status='cancelled' WHERE id=?1").bind(f.jobId).run();}});vi.stubGlobal('fetch',request);await runMediaJob(env,f.jobId,f.versionId);expect((await getJob(env,f.jobId)).status).toBe('cancelled');expect(await env.DB.prepare('SELECT COUNT(*) n FROM source_fragments WHERE source_version_id=?1').bind(f.versionId).first()).toEqual({n:0});expect(request.mock.calls.some(([,init])=>init?.method==='DELETE')).toBe(true);});
 it('retries supplier cleanup without repeating generation',async()=>{const f=await sourceFixture(),request=mockProvider({cleanupFail:true});vi.stubGlobal('fetch',request);await runMediaJob(env,f.jobId,f.versionId);expect(await env.DB.prepare('SELECT cleanup_pending FROM media_processing WHERE job_id=?1').bind(f.jobId).first()).toEqual({cleanup_pending:1});const cleanup=mockProvider();vi.stubGlobal('fetch',cleanup);await cleanupMediaFiles(env);expect(cleanup.mock.calls.every(([,init])=>init?.method==='DELETE')).toBe(true);});
 it('rejects returned upload locations outside Google before streaming credentials',async()=>{const {model}=await modelFixture(),request=vi.fn(async()=>new Response('{}',{headers:{'x-goog-upload-url':'https://evil.example/upload/file'}}));const client=new GeminiMediaClient(model,'fixture-media-key',request);await expect(client.upload(new ReadableStream(),1,'video/mp4','fixture')).rejects.toThrow('非官方上传地址');expect(request).toHaveBeenCalledTimes(1);});
 it('resumes durable windows without reuploading or replaying completed calls',async()=>{const f=await sourceFixture(),request=mockProvider({duration:1300});vi.stubGlobal('fetch',request);expect(await runMediaJob(env,f.jobId,f.versionId,1)).toEqual({status:'running'});expect(await runMediaJob(env,f.jobId,f.versionId,1)).toEqual({status:'running'});expect(await runMediaJob(env,f.jobId,f.versionId,1)).toEqual({status:'succeeded'});expect(request.mock.calls.filter(([url])=>String(url).endsWith('/upload/v1beta/files'))).toHaveLength(1);expect(request.mock.calls.filter(([url])=>String(url).includes(':generateContent'))).toHaveLength(3);expect(request.mock.calls.filter(([,init])=>init?.method==='DELETE')).toHaveLength(1);});
 it('duplicate delivery cannot fail or clean the worker holding a live lease',async()=>{const f=await sourceFixture(),config=(await loadAiConfig(env.DB))!,stateId=newId();await env.DB.prepare("INSERT INTO media_processing(id,job_id,source_version_id,config_version_id,stage,provider_name,provider_uri,lease_token,lease_expires_at,created_at,updated_at) VALUES(?1,?2,?3,?4,'generating','files/fixture','https://generativelanguage.googleapis.com/v1beta/files/fixture','other-worker',?5,?6,?6)").bind(stateId,f.jobId,f.versionId,config.id,new Date(Date.now()+900000).toISOString(),nowIso()).run();const request=mockProvider();vi.stubGlobal('fetch',request);expect(await runMediaJob(env,f.jobId,f.versionId)).toEqual({status:'busy'});expect((await getJob(env,f.jobId)).status).toBe('running');expect(await env.DB.prepare('SELECT stage,lease_token FROM media_processing WHERE id=?1').bind(stateId).first()).toEqual({stage:'generating',lease_token:'other-worker'});expect(request).not.toHaveBeenCalled();});
 it('finite budget rejects media before uploading to Google',async()=>{const f=await sourceFixture();await env.DB.prepare('UPDATE projects SET ai_budget_usd=100 WHERE id=?1').bind(f.projectId).run();const request=mockProvider();vi.stubGlobal('fetch',request);expect(await runMediaJob(env,f.jobId,f.versionId)).toEqual({status:'failed'});expect(request).not.toHaveBeenCalled();});
 it('unknown modality usage or missing media prices never produces falsely precise cost',async()=>{const {model}=await modelFixture();expect(mediaCost(model,{promptTokens:10,completionTokens:2,inputDetails:[]})).toBeNull();expect(mediaCost(model,{promptTokens:10,completionTokens:2,inputDetails:[{modality:'IMAGE',tokenCount:10}]})).toBeNull();expect(mediaCost({...model,mediaInputPricePerMTokens:undefined},{promptTokens:10,completionTokens:2,inputDetails:[{modality:'AUDIO',tokenCount:10}]})).toBeNull();expect(mediaCost(model,{promptTokens:10,completionTokens:2,inputDetails:[{modality:'AUDIO',tokenCount:10}]})).toBe(24/1e6);});
 it('rejects untrusted file URIs before generation and provides a free metadata probe',async()=>{const {model}=await modelFixture(),request=vi.fn(async()=>Response.json({supportedGenerationMethods:['generateContent']}));const client=new GeminiMediaClient(model,'fixture-media-key',request);await expect(client.summarize({name:'files/fixture',uri:'http://127.0.0.1/private'},'video/mp4')).rejects.toThrow('URI');expect(request).not.toHaveBeenCalled();expect(await client.probe()).toBe(true);expect(request.mock.calls).toHaveLength(1);});
 it('blocks included pending draft media, then promotes ready summary without paid replay',async()=>{const f=await draftFixture(),row=await getDraft(env,f.draftId,f.owner.userId);await expect(prepareDraftPreviewAttempt(env,row,newId())).rejects.toThrow('仍在处理');const request=mockProvider();vi.stubGlobal('fetch',request);expect(await runMediaJob(env,f.jobId)).toEqual({status:'succeeded'});const ready=await getDraft(env,f.draftId,f.owner.userId);expect(ready.revision).toBe(2);expect((await draftView(env,ready)).files[0]).toMatchObject({textReady:true,mediaStatus:'ready'});await env.DB.prepare("UPDATE project_creation_drafts SET preview_json=?2,preview_state='ready',preview_revision=revision,preview_attempt_id=?3 WHERE id=?1").bind(f.draftId,JSON.stringify({mode:'manual',tasks:[]}),newId()).run();await commitDraft(env,f.draftId,f.owner.userId,2);const processing=await env.DB.prepare('SELECT summary_status FROM source_processing p JOIN source_versions v ON v.id=p.source_version_id WHERE v.file_id=?1').bind(f.fileId).first();expect(processing).toEqual({summary_status:'ready'});const promoted=await env.DB.prepare('SELECT draft_file_id,source_version_id FROM media_processing WHERE job_id=?1').bind(f.jobId).first<{draft_file_id:string|null;source_version_id:string|null}>();expect(promoted?.draft_file_id).toBeNull();expect(promoted?.source_version_id).toBeTruthy();expect(request.mock.calls.filter(([url])=>String(url).includes(':generateContent'))).toHaveLength(1);});
 it('removed draft media prevents the paid call and preserves original',async()=>{const f=await draftFixture();await env.DB.prepare('UPDATE creation_draft_files SET removed=1 WHERE id=?1').bind(f.fileId).run();const request=mockProvider();vi.stubGlobal('fetch',request);await runMediaJob(env,f.jobId);expect(request).not.toHaveBeenCalled();expect(await env.FILES.head('draft-media/'+f.fileId)).toBeTruthy();});
 it('extracts requirements from a ready media summary through the text model without repeating Gemini',async()=>{
  const f=await sourceFixture();vi.stubGlobal('fetch',mockProvider());await runMediaJob(env,f.jobId,f.versionId);
  await configureGoFixture();const config=(await loadAiConfig(env.DB))!,jobId=newId();
  await env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,attempts,created_at,updated_at) VALUES(?1,?2,'parse_source','running',?3,0,?4,?4)").bind(jobId,f.projectId,JSON.stringify({sourceVersionId:f.versionId,sourceLifecycleVersion:1,phase:'extract',configVersionId:config.id}),nowIso()).run();
  const request=vi.fn(async(url:RequestInfo|URL,init?:RequestInit)=>{expect(String(url)).toContain('opencode.ai/zen/go');const input=JSON.parse(String(init?.body));expect(input.model).toBe('glm-5.2');expect(input.messages[0].content).toContain('音视频 AI 摘要');return Response.json({choices:[{message:{content:JSON.stringify({requirements:[]})}}],usage:{prompt_tokens:42,completion_tokens:17}});});
  vi.stubGlobal('fetch',request);expect(await runParseJob(env,jobId)).toEqual({status:'succeeded'});expect(request).toHaveBeenCalledTimes(1);expect(await env.DB.prepare('SELECT requirements_status,summary_status FROM source_processing WHERE source_version_id=?1').bind(f.versionId).first()).toEqual({requirements_status:'ready',summary_status:'ready'});expect(await env.DB.prepare('SELECT COUNT(*) n FROM requirement_sets WHERE source_version_id=?1').bind(f.versionId).first()).toEqual({n:1});
 });
});
