import { afterEach, describe, expect, it, vi } from 'vitest';
import { env } from './helpers/env';
import { seedProject, seedUser } from './helpers/seed';
import { loadAiConfig, resolveAiConfig } from '../src/ai/config';
import { seal } from '../src/ai/secrets';
import { GeminiMediaClient, validateMediaModel } from '../src/ai/gemini-media';
import { newId, nowIso } from '../src/core/db';
import { uploadLimit, validateUploadBytes } from '../src/services/files';
import { runMediaJob, cleanupMediaFiles } from '../src/services/media-summary';
import { getJob } from '../src/services/jobs';

afterEach(()=>vi.unstubAllGlobals());
const output={title:'录像摘要',summary:'展示了试验过程',keyPoints:['试验结果'],conclusions:['成功'],actionItems:[],timestamps:[{seconds:2,description:'试验开始'}],caveats:[],complete:true,durationSeconds:30};
async function modelFixture(){const config=(await loadAiConfig(env.DB))!;const model={...config.config.textEconomy,provider:'openai-compatible',providerPreset:'gemini' as const,model:'gemini-2.5-flash',apiUrl:'https://generativelanguage.googleapis.com',apiKeyEncrypted:await seal('fixture-media-key',env.AUTH_SECRET),pricePerMTokens:[1,2] as [number,number]};config.config.mediaUnderstanding=model;await env.DB.prepare('UPDATE ai_config_versions SET config_json=?2,enabled=1 WHERE id=?1').bind(config.id,JSON.stringify(config.config)).run();return {config,model};}
async function sourceFixture(){const owner=await seedUser(),projectId=await seedProject(owner.userId),fileId=newId(),sourceId=newId(),versionId=newId(),jobId=newId(),now=nowIso();const {config}=await modelFixture();await env.FILES.put('fixture-media/'+fileId,new Uint8Array([0,0,0,16,102,116,121,112]));await env.DB.batch([
env.DB.prepare("INSERT INTO files(id,project_id,uploader_user_id,r2_key,ext,mime_detected,size_bytes,status,created_at) VALUES(?1,?2,?3,?4,'.mp4','video/mp4',8,'available',?5)").bind(fileId,projectId,owner.userId,'fixture-media/'+fileId,now),
env.DB.prepare("INSERT INTO sources(id,project_id,kind,title,current_version_id,created_by,created_at,updated_at) VALUES(?1,?2,'file','录制',?3,?4,?5,?5)").bind(sourceId,projectId,versionId,owner.userId,now),
env.DB.prepare("INSERT INTO source_versions(id,source_id,project_id,revision,origin,file_id,status,created_at) VALUES(?1,?2,?3,1,'file',?4,'pending',?5)").bind(versionId,sourceId,projectId,fileId,now),
env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,attempts,created_at,updated_at) VALUES(?1,?2,'parse_source','running',?3,0,?4,?4)").bind(jobId,projectId,JSON.stringify({sourceVersionId:versionId,sourceLifecycleVersion:1,configVersionId:config.id,phase:'extract'}),now),
]);return {projectId,fileId,sourceId,versionId,jobId};}
function mockProvider(options:{duration?:number;truncate?:boolean;complete?:boolean;cleanupFail?:boolean;generateError?:boolean;afterGenerate?:()=>Promise<void>}={}){
return vi.fn(async(url:RequestInfo|URL,init?:RequestInit)=>{
 const value=String(url);expect(new Headers(init?.headers).get('x-goog-api-key')).toBe('fixture-media-key');
 if(init?.method==='DELETE'){if(options.cleanupFail)return new Response('',{status:500});return new Response('{}');}
 if(value.endsWith('/upload/v1beta/files'))return new Response('{}',{headers:{'x-goog-upload-url':'https://generativelanguage.googleapis.com/upload/v1beta/files?upload_id=fixture'}});
 if(value.includes('upload_id=')){expect(init?.body).toBeInstanceOf(ReadableStream);return Response.json({file:{name:'files/fixture',uri:'https://generativelanguage.googleapis.com/v1beta/files/fixture',state:'ACTIVE'}});}
 if(value.includes(':generateContent')){if(options.generateError)throw new Error('connection reset');await options.afterGenerate?.();const body=JSON.parse(String(init?.body));const start=Number.parseFloat(body.contents[0].parts[0].video_metadata?.start_offset??'0');return Response.json({candidates:[{finishReason:options.truncate?'MAX_TOKENS':'STOP',content:{parts:[{text:JSON.stringify({...output,complete:options.complete??true,timestamps:[{seconds:start+2,description:'事件'}]})}]}}],usageMetadata:{promptTokenCount:100, candidatesTokenCount:40}});}
 return Response.json({name:'files/fixture',uri:'https://generativelanguage.googleapis.com/v1beta/files/fixture',state:'ACTIVE',videoMetadata:{videoDuration:(options.duration??30)+'s'}});
});}
describe('Gemini media processing',()=>{
 it.each([['.mp3',[73,68,51],'audio/mpeg'],['.wav',[82,73,70,70,0,0,0,0,87,65,86,69],'audio/wav'],['.m4a',[0,0,0,16,102,116,121,112],'audio/mp4'],['.mp4',[0,0,0,16,102,116,121,112],'video/mp4'],['.webm',[26,69,223,163],'video/webm']] as const)('validates %s magic without an application file size limit',(ext,bytes,mime)=>{expect(validateUploadBytes(ext,new Uint8Array(bytes))).toBe(mime);expect(uploadLimit(ext)).toBeNull();expect(()=>validateUploadBytes(ext,new Uint8Array([1,2,3]))).toThrow();});
 it('removes application size limits while rejecting invalid media magic',()=>{expect(uploadLimit('.pdf')).toBeNull();expect(()=>validateUploadBytes('.mp4',new Uint8Array(50*1024*1024+1))).toThrow();});
 it('keeps independent media config in unified mode',async()=>{const {config,model}=await modelFixture();expect(resolveAiConfig({...config.config,routingMode:'unified',unified:config.config.review}).mediaUnderstanding).toBe(model);expect(()=>validateMediaModel({...model,apiUrl:'https://other.example'})).toThrow();});
 it('uploads streams, saves labelled summary and timestamp metadata, accounts usage, removes provider file',async()=>{const f=await sourceFixture(),request=mockProvider();vi.stubGlobal('fetch',request);expect(await runMediaJob(env,f.jobId,f.versionId)).toEqual({status:'succeeded'});const fragment=await env.DB.prepare('SELECT content FROM source_fragments WHERE source_version_id=?1').bind(f.versionId).first<{content:string}>();expect(fragment?.content).toContain('AI 摘要（非逐字原文）');const state=await env.DB.prepare('SELECT summary_json,cleanup_pending FROM media_processing WHERE job_id=?1').bind(f.jobId).first<{summary_json:string;cleanup_pending:number}>();expect(JSON.parse(state!.summary_json).timestamps).toHaveLength(1);expect(state?.cleanup_pending).toBe(0);expect(await env.DB.prepare('SELECT cost_status FROM media_calls WHERE job_id=?1').bind(f.jobId).first()).toEqual({cost_status:'known'});});
 it('splits long video into persisted 600 second windows',async()=>{const f=await sourceFixture(),request=mockProvider({duration:1300});vi.stubGlobal('fetch',request);await runMediaJob(env,f.jobId,f.versionId);const state=await env.DB.prepare('SELECT windows_json FROM media_processing WHERE job_id=?1').bind(f.jobId).first<{windows_json:string}>();expect(JSON.parse(state!.windows_json)).toHaveLength(3);expect(request.mock.calls.filter(([url])=>String(url).includes(':generateContent'))).toHaveLength(3);});
 it('marks truncation failure and never replays an ambiguous paid call',async()=>{const f=await sourceFixture(),request=mockProvider({truncate:true});vi.stubGlobal('fetch',request);expect(await runMediaJob(env,f.jobId,f.versionId)).toEqual({status:'failed'});await runMediaJob(env,f.jobId,f.versionId);expect(request.mock.calls.filter(([url])=>String(url).includes(':generateContent'))).toHaveLength(1);expect(await env.DB.prepare('SELECT status FROM usage_reservations WHERE job_id=?1').bind(f.jobId).first()).toEqual({status:'pending_reconcile'});});
 it('persists partial results without marking them complete',async()=>{const f=await sourceFixture();vi.stubGlobal('fetch',mockProvider({complete:false}));await runMediaJob(env,f.jobId,f.versionId);const state=await env.DB.prepare('SELECT stage,summary_json FROM media_processing WHERE job_id=?1').bind(f.jobId).first<{stage:string;summary_json:string}>();expect(state?.stage).toBe('failed');expect(JSON.parse(state!.summary_json).complete).toBe(false);expect(await env.DB.prepare('SELECT COUNT(*) n FROM source_fragments WHERE source_version_id=?1').bind(f.versionId).first()).toEqual({n:0});});
 it('does not apply results after cancellation and still cleans provider files',async()=>{const f=await sourceFixture(),request=mockProvider({afterGenerate:async()=>{await env.DB.prepare("UPDATE jobs SET status='cancelled' WHERE id=?1").bind(f.jobId).run();}});vi.stubGlobal('fetch',request);await runMediaJob(env,f.jobId,f.versionId);expect((await getJob(env,f.jobId)).status).toBe('cancelled');expect(await env.DB.prepare('SELECT COUNT(*) n FROM source_fragments WHERE source_version_id=?1').bind(f.versionId).first()).toEqual({n:0});expect(request.mock.calls.some(([,init])=>init?.method==='DELETE')).toBe(true);});
 it('retries supplier cleanup without repeating generation',async()=>{const f=await sourceFixture(),request=mockProvider({cleanupFail:true});vi.stubGlobal('fetch',request);await runMediaJob(env,f.jobId,f.versionId);expect(await env.DB.prepare('SELECT cleanup_pending FROM media_processing WHERE job_id=?1').bind(f.jobId).first()).toEqual({cleanup_pending:1});const cleanup=mockProvider();vi.stubGlobal('fetch',cleanup);await cleanupMediaFiles(env);expect(cleanup.mock.calls.every(([,init])=>init?.method==='DELETE')).toBe(true);});
 it('rejects returned upload locations outside Google before streaming credentials',async()=>{const {model}=await modelFixture(),request=vi.fn(async()=>new Response('{}',{headers:{'x-goog-upload-url':'https://evil.example/upload/file'}}));const client=new GeminiMediaClient(model,'fixture-media-key',request);await expect(client.upload(new ReadableStream(),1,'video/mp4','fixture')).rejects.toThrow('非官方上传地址');expect(request).toHaveBeenCalledTimes(1);});
});
