import {afterEach,describe,it,expect,vi} from 'vitest';
import {env} from './helpers/env';
import {seedProject,seedUser} from './helpers/seed';
import {newId,nowIso} from '../src/core/db';
import {loadAiConfig} from '../src/ai/config';
import {configureGoFixture} from './helpers/provider-config';
import {transcriptGate,chunkTranscript,allQualityPassed,WHISPER_MODEL,type Transcript} from '../src/ai/whisper';
import {runMediaJob} from '../src/services/media-summary';
import {readAudioPipelineStatus,resumeWaitingAudioFallback} from '../src/services/audio-pipeline';
import {getJob} from '../src/services/jobs';
import {seal} from '../src/ai/secrets';
const transcript:Transcript={text:'本次会议确认测试通过，下一步发布。',transcription_info:{duration:30,language_probability:0.1},segments:[{start:0,end:20,text:'本次会议确认测试通过，下一步发布。',avg_logprob:-0.5,no_speech_prob:0.01,compression_ratio:1.2}]};
const q={score:0.95,critical:false,reasons:[],anomalies:[]};
const summary={title:'会议',summary:'测试通过，计划发布。',keyPoints:['测试通过'],conclusions:['发布'],actionItems:['执行发布'],timestamps:[{seconds:5,description:'确认测试'}],caveats:[],complete:true};
afterEach(()=>vi.unstubAllGlobals());
async function fixture(t=transcript){await configureGoFixture();const config=(await loadAiConfig(env.DB))!;const owner=await seedUser(),projectId=await seedProject(owner.userId),fileId=newId(),versionId=newId(),sourceId=newId(),jobId=newId(),now=nowIso();const r2='audio-test/'+fileId;await env.FILES.put(r2,new Uint8Array([82,73,70,70]));await env.DB.batch([
env.DB.prepare("INSERT INTO files(id,project_id,uploader_user_id,r2_key,ext,mime_detected,size_bytes,status,created_at) VALUES(?1,?2,?3,?4,'.wav','audio/wav',4,'available',?5)").bind(fileId,projectId,owner.userId,r2,now),
env.DB.prepare("INSERT INTO sources(id,project_id,kind,title,current_version_id,created_by,created_at,updated_at) VALUES(?1,?2,'file','音频',?3,?4,?5,?5)").bind(sourceId,projectId,versionId,owner.userId,now),
env.DB.prepare("INSERT INTO source_versions(id,source_id,project_id,revision,origin,file_id,status,created_at) VALUES(?1,?2,?3,1,'file',?4,'pending',?5)").bind(versionId,sourceId,projectId,fileId,now),
env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,attempts,created_by,created_at,updated_at) VALUES(?1,?2,'parse_source','running',?3,0,?4,?5,?5)").bind(jobId,projectId,JSON.stringify({sourceVersionId:versionId,sourceLifecycleVersion:1,configVersionId:config.id,phase:'extract'}),owner.userId,now)]);
const run=vi.fn(async(model:string,input:unknown)=>{expect(model).toBe(WHISPER_MODEL);expect(input).toMatchObject({task:'transcribe',vad_filter:true});expect((input as {audio:{body:unknown}}).audio.body).toBeInstanceOf(ReadableStream);return t;});return {config,owner,jobId,versionId,projectId,run,local:{...env,AI:{run},AGENT_WORKFLOW:{create:vi.fn(async()=>({}))}} as unknown as typeof env};}
function llm(values:unknown[]){let i=0;const request=vi.fn(async(_url:RequestInfo|URL,init?:RequestInit)=>{const input=JSON.parse(String(init?.body));expect(input.messages[0].content).not.toContain('持续项目反馈');return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(values[i++])}}],usage:{prompt_tokens:10,completion_tokens:20}});});vi.stubGlobal('fetch',request);return request;}
describe('Whisper conservative gates',()=>{
 it('does not mistake language probability for transcript accuracy',()=>expect(transcriptGate(transcript)).toEqual([]));
 for(const [name,patch] of [['low logprob',{avg_logprob:-1.01}],['speech probability boundary',{no_speech_prob:0.6}],['compression boundary',{compression_ratio:2.41}],['missing metric',{avg_logprob:undefined}],['invalid times',{end:31}]] as const){it(name,()=>expect(transcriptGate({...transcript,segments:[{...transcript.segments![0],...patch}]})).not.toEqual([]));}
 it('accepts inclusive logprob and compression thresholds',()=>expect(transcriptGate({...transcript,segments:[{...transcript.segments![0],avg_logprob:-1,compression_ratio:2.4}]})).toEqual([]));
 it('rejects empty/silent transcripts',()=>expect(transcriptGate({text:'',segments:[]})).not.toEqual([]));
 it('rejects mismatched full text and segments',()=>expect(transcriptGate({...transcript,text:'different'})).not.toEqual([]));
 it('preserves whole segments and timestamps',()=>expect(chunkTranscript(transcript,16000)[0]).toMatchObject({start:0,end:20,segments:transcript.segments}));
 it('rejects oversized complete segments instead of truncating',()=>expect(()=>chunkTranscript({...transcript,segments:[{...transcript.segments![0],text:'a'.repeat(12001)}]},16000)).toThrow());
 it('requires every quality block and 0.85 inclusive',()=>{expect(allQualityPassed([{...q,score:0.85}],1)).toBe(true);expect(allQualityPassed([q],2)).toBe(false);expect(allQualityPassed([{...q,score:0.849}],1)).toBe(false);});
});
describe('durable native audio path',()=>{
 it('transcribes then checks all blocks before summary and records separated billing',async()=>{const f=await fixture(),request=llm([q,summary]);expect(await runMediaJob(f.local,f.jobId,f.versionId)).toEqual({status:'succeeded'});expect(f.run).toHaveBeenCalledOnce();expect(request).toHaveBeenCalledTimes(2);expect(await readAudioPipelineStatus(f.local,f.jobId)).toMatchObject({phase:'ready',qualityScore:0.95,transcriptAvailable:true});expect(await env.DB.prepare('SELECT cost_usd,cost_status FROM media_calls WHERE job_id=?1').bind(f.jobId).first()).toEqual({cost_usd:0.0002565,cost_status:'known'});expect(await env.DB.prepare('SELECT COUNT(*) n FROM ai_calls WHERE job_id=?1').bind(f.jobId).first()).toEqual({n:2});expect(await runMediaJob(f.local,f.jobId,f.versionId)).toEqual({status:'succeeded'});expect(f.run).toHaveBeenCalledOnce();});
 it('saves stage checkpoints and reuses transcription across slices',async()=>{const f=await fixture(),request=llm([q,summary]);expect(await runMediaJob(f.local,f.jobId,f.versionId,1)).toEqual({status:'running'});expect(request).not.toHaveBeenCalled();expect(await runMediaJob(f.local,f.jobId,f.versionId,1)).toEqual({status:'running'});expect(request).toHaveBeenCalledOnce();expect(await runMediaJob(f.local,f.jobId,f.versionId,1)).toEqual({status:'succeeded'});expect(f.run).toHaveBeenCalledOnce();});
 it('waits for Gemini without generating summary if quality is too low',async()=>{const f=await fixture(),request=llm([{...q,score:0.8}]);expect(await runMediaJob(f.local,f.jobId,f.versionId)).toEqual({status:'waiting_input'});expect(request).toHaveBeenCalledOnce();expect(await readAudioPipelineStatus(f.local,f.jobId)).toMatchObject({phase:'waiting_config',canResumeFallback:false,transcriptAvailable:true});expect(await env.DB.prepare('SELECT char_count FROM source_versions WHERE id=?1').bind(f.versionId).first()).toEqual({char_count:null});expect(await runMediaJob(f.local,f.jobId,f.versionId)).toEqual({status:'waiting_input'});expect(f.run).toHaveBeenCalledOnce();});
 it('missing metrics skip quality and wait for Gemini',async()=>{const f=await fixture({...transcript,segments:[{...transcript.segments![0],avg_logprob:undefined}]});const request=llm([]);expect(await runMediaJob(f.local,f.jobId,f.versionId)).toEqual({status:'waiting_input'});expect(request).not.toHaveBeenCalled();});
 it('never replays uncertain Whisper requests',async()=>{const f=await fixture();f.run.mockRejectedValueOnce(new Error('network'));const request=llm([]);expect(await runMediaJob(f.local,f.jobId,f.versionId)).toEqual({status:'failed'});expect((await readAudioPipelineStatus(f.local,f.jobId))?.phase).toBe('unknown');await runMediaJob(f.local,f.jobId,f.versionId);expect(f.run).toHaveBeenCalledOnce();expect(request).not.toHaveBeenCalled();});
 it('cancellation prevents summaries after transcription',async()=>{const f=await fixture();await runMediaJob(f.local,f.jobId,f.versionId,1);await env.DB.prepare("UPDATE jobs SET status='cancelled' WHERE id=?1").bind(f.jobId).run();const request=llm([]);expect(await runMediaJob(f.local,f.jobId,f.versionId)).toEqual({status:'cancelled'});expect(request).not.toHaveBeenCalled();});
 it('resumes waiting job with latest frozen Gemini config and blocks outsiders',async()=>{const f=await fixture();llm([{...q,critical:true}]);await runMediaJob(f.local,f.jobId,f.versionId);const outsider=await seedUser();await expect(resumeWaitingAudioFallback(f.local,f.jobId,outsider.userId)).rejects.toThrow('项目成员');const model={...f.config.config.textEconomy,provider:'google-gemini',providerPreset:'gemini',model:'gemini-2.5-flash',apiUrl:'https://generativelanguage.googleapis.com',apiKeyEncrypted:await seal('fixture-media',env.AUTH_SECRET)};await env.DB.prepare('UPDATE ai_config_versions SET config_json=?2 WHERE id=?1').bind(f.config.id,JSON.stringify({...f.config.config,mediaUnderstanding:model})).run();expect(await readAudioPipelineStatus(f.local,f.jobId)).toMatchObject({canResumeFallback:true});expect(await resumeWaitingAudioFallback(f.local,f.jobId,f.owner.userId)).toMatchObject({jobId:f.jobId,status:'running'});await expect(resumeWaitingAudioFallback(f.local,f.jobId,f.owner.userId)).rejects.toThrow('已继续');expect(f.run).toHaveBeenCalledOnce();expect((await getJob(env,f.jobId)).status).toBe('running');});
});

