import { afterEach, describe, expect, it, vi } from 'vitest';
import { env, BASE } from './helpers/env';
import { seedProject, seedUser, authCookie } from './helpers/seed';
import { configureGoFixture, assertGoRequest } from './helpers/provider-config';
import { createApp } from '../src/app';
import type { Env } from '../src/env';
import { sha256Hex } from '../src/core/db';
import { approveBridgePairing, bridgeDeviceDto, bridgeArtifactInit, bridgeInput, browserBridgeHandoff, cancelBridgeHandoff, claimBridgeHandoff, completeBridgeHandoff, createBridgeHandoff, createBridgePairing, deviceBridgeHandoff, loadBridgeDevice, loadBridgeHandoff, recordBridgeEvent, refreshBridgeHandoff, storeBridgeArtifact } from '../src/services/agent-bridges';
import { adoptBridgeResult } from '../src/services/agent-bridge-adoption';
import { runAiJob } from '../src/services/ai-jobs';
import { saveStandard } from '../src/services/project-simplification';
import { bridgeSnapshot } from '../src/services/agent-bridges';
import { createFileInit, storeFileContent } from '../src/services/files';
import { gcOrphanObjects } from '../src/services/gc';
await configureGoFixture();afterEach(()=>vi.unstubAllGlobals());
const offline={...env,AGENT_WORKFLOW:{create:async()=>{throw new Error('offline');}}} as unknown as Env;
async function fixture(){
 await env.DB.prepare('UPDATE ai_config_versions SET enabled=1').run();const user=await seedUser(),projectId=await seedProject(user.userId),taskId=crypto.randomUUID(),now=new Date().toISOString(),secret=crypto.randomUUID()+crypto.randomUUID();
 await env.DB.batch([env.DB.prepare('UPDATE projects SET ai_collaboration_enabled=1 WHERE id=?1').bind(projectId),env.DB.prepare("INSERT INTO tasks(id,project_id,title,detail,criteria,status,lifecycle_state,revision,created_by,assignee_id,created_at,updated_at) VALUES(?1,?2,'数字资料分析','分析已提供的文件，输出报告','提交报告','doing','in_progress',1,?3,?3,?4,?4)").bind(taskId,projectId,user.userId,now)]);
 const pair=await createBridgePairing(env,{credentialHash:await sha256Hex(secret),deviceName:'Desktop',bridgeVersion:'0.1.0',dshVersion:'0.2.0-rc.2'},BASE);await approveBridgePairing(env,pair.pairingId,user.userId,[projectId]);await env.DB.prepare('UPDATE agent_bridge_scopes SET workspace_label=?2 WHERE device_id=?1').bind(pair.pairingId,'Office').run();const device=await loadBridgeDevice(env,'Bearer '+secret);
 return{user,projectId,taskId,secret,pair,device,start:()=>createBridgeHandoff(offline,projectId,taskId,user.userId,{expectedRevision:1,targetDeviceId:device.id},crypto.randomUUID())};
}
async function ready(f:Awaited<ReturnType<typeof fixture>>){const h=await f.start(),job=await env.DB.prepare('SELECT job_id FROM task_agent_eligibility WHERE task_id=?1').bind(f.taskId).first<{job_id:string}>();const provider=vi.fn(async(url:RequestInfo|URL,init?:RequestInit)=>{assertGoRequest(url,init);return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({eligible:true,reason:'资料分析可独立执行'})}}],usage:{prompt_tokens:30,completion_tokens:20}}),{headers:{'content-type':'application/json'}});});vi.stubGlobal('fetch',provider);await runAiJob(env,job!.job_id);const row=await refreshBridgeHandoff(env,await loadBridgeHandoff(env,h.handoffId));expect(row.state).toBe('waiting_device');return row;}
async function running(f:Awaited<ReturnType<typeof fixture>>){await ready(f);const h=(await claimBridgeHandoff(env,f.device))!;let r=await loadBridgeHandoff(env,h.handoffId);await recordBridgeEvent(env,r,{sequence:1,type:'session_created',sessionId:'session-1'});r=await loadBridgeHandoff(env,r.id);await recordBridgeEvent(env,r,{sequence:2,type:'prompt_accepted',sessionId:'session-1'});return loadBridgeHandoff(env,r.id);}
describe('DSH bridge capability and durable handoff',()=>{
 it('pairs only with current project members; device hash cannot authenticate as a secret',async()=>{const f=await fixture(),other=await seedUser();await expect(approveBridgePairing(env,f.pair.pairingId,other.userId,[f.projectId])).rejects.toMatchObject({code:'PERMISSION_DENIED'});await expect(loadBridgeDevice(env,'Bearer '+await sha256Hex(f.secret))).rejects.toMatchObject({code:'UNAUTHENTICATED'});expect(await bridgeDeviceDto(env,f.device)).toMatchObject({paired:true,protocolVersion:1,projects:[{projectId:f.projectId,workspaceLabel:'Office'}]});});
 it('expires unapproved pairing and enforces project ownership',async()=>{const f=await fixture(),secret=crypto.randomUUID()+crypto.randomUUID(),p=await createBridgePairing(env,{credentialHash:await sha256Hex(secret),deviceName:'other',bridgeVersion:'1',dshVersion:'1'},BASE);await env.DB.prepare('UPDATE agent_bridge_devices SET pairing_expires_at=?2 WHERE id=?1').bind(p.pairingId,'2000-01-01T00:00:00.000Z').run();await expect(approveBridgePairing(env,p.pairingId,f.user.userId,[f.projectId])).rejects.toMatchObject({code:'INVALID_STATE'});});
 it('starts model check once, deduplicates handoff and validates revision',async()=>{const f=await fixture(),key=crypto.randomUUID(),p={expectedRevision:1,targetDeviceId:f.device.id};const a=await createBridgeHandoff(offline,f.projectId,f.taskId,f.user.userId,p,key),b=await createBridgeHandoff(offline,f.projectId,f.taskId,f.user.userId,p,key);expect(a.handoffId).toBe(b.handoffId);expect(a.state).toBe('checking');expect(await env.DB.prepare('SELECT COUNT(*) n FROM task_agent_eligibility WHERE task_id=?1').bind(f.taskId).first()).toEqual({n:1});await expect(createBridgeHandoff(offline,f.projectId,f.taskId,f.user.userId,{...p,expectedRevision:2},key)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});await expect(createBridgeHandoff(offline,f.projectId,f.taskId,f.user.userId,{...p,expectedRevision:2},crypto.randomUUID())).rejects.toMatchObject({code:'VERSION_CONFLICT'});});
 it('blocks failed and negative semantic judgments without dispatch',async()=>{const f=await fixture(),h=await f.start();await env.DB.prepare("UPDATE task_agent_eligibility SET status='ready',eligible=0,reason='必须到场采访' WHERE task_id=?1").bind(f.taskId).run();expect((await refreshBridgeHandoff(env,await loadBridgeHandoff(env,h.handoffId))).state).toBe('blocked');expect(await claimBridgeHandoff(env,f.device)).toBeNull();});
 it('atomically claims one run and retries always return same sticky run',async()=>{const f=await fixture(),r=await ready(f);const [a,b]=await Promise.all([claimBridgeHandoff(env,f.device),claimBridgeHandoff(env,f.device)]);expect(a!.handoffId).toBe(r.id);expect(b!.handoffId).toBe(r.id);expect((await claimBridgeHandoff(env,f.device))!.handoffId).toBe(r.id);});
 it('blocks task/context edits before claim; queue expires after 24 hours',async()=>{const f=await fixture(),r=await ready(f);await env.DB.prepare("UPDATE tasks SET criteria='新标准',revision=2 WHERE id=?1").bind(f.taskId).run();expect(await claimBridgeHandoff(env,f.device)).toBeNull();expect(await loadBridgeHandoff(env,r.id)).toMatchObject({state:'blocked',stale:1});const g=await fixture(),h=await ready(g);await env.DB.prepare("UPDATE agent_bridge_handoffs SET expires_at='2000-01-01T00:00:00Z' WHERE id=?1").bind(h.id).run();expect(await claimBridgeHandoff(env,g.device)).toBeNull();});
 it('denies removed membership/revoked device and cross-device access',async()=>{const f=await fixture(),r=await running(f),g=await fixture();await expect(deviceBridgeHandoff(env,r.id,g.device)).rejects.toMatchObject({code:'PERMISSION_DENIED'});await expect(browserBridgeHandoff(env,r.id,g.user.userId)).rejects.toMatchObject({code:'PERMISSION_DENIED'});await env.DB.prepare('DELETE FROM project_members WHERE project_id=?1 AND user_id=?2').bind(f.projectId,f.user.userId).run();await expect(deviceBridgeHandoff(env,r.id,f.device)).rejects.toMatchObject({code:'PERMISSION_DENIED'});});
 it('deduplicates events and rejects conflicting payload/session changes',async()=>{const f=await fixture(),r=await running(f);const event={sequence:3,type:'waiting_input' as const,message:'审批',sessionId:'session-1'};expect((await recordBridgeEvent(env,r,event)).state).toBe('waiting_input');expect((await recordBridgeEvent(env,r,event)).state).toBe('waiting_input');await expect(recordBridgeEvent(env,r,{...event,message:'other'})).rejects.toMatchObject({code:'INVALID_STATE'});await expect(recordBridgeEvent(env,await loadBridgeHandoff(env,r.id),{sequence:4,type:'running',sessionId:'other'})).rejects.toMatchObject({code:'INVALID_STATE'});});
 it('never retries uncertain dispatch and requires cancellation acknowledgement',async()=>{const f=await fixture(),r=await running(f);await recordBridgeEvent(env,r,{sequence:3,type:'dispatch_uncertain',sessionId:'session-1'});const uncertain=await loadBridgeHandoff(env,r.id);expect((await claimBridgeHandoff(env,f.device))!.state).toBe('dispatch_uncertain');await expect(recordBridgeEvent(env,uncertain,{sequence:4,type:'running',sessionId:'session-1'})).rejects.toMatchObject({code:'INVALID_STATE'});await cancelBridgeHandoff(env,uncertain);expect((await loadBridgeHandoff(env,r.id)).state).toBe('cancel_requested');await recordBridgeEvent(env,await loadBridgeHandoff(env,r.id),{sequence:4,type:'cancelled'});expect((await loadBridgeHandoff(env,r.id)).state).toBe('cancelled');});
 it('restricts snapshot files and validates safe names, bytes, manifests and resume uploads',async()=>{const f=await fixture(),r=await running(f),bytes=new TextEncoder().encode('分析报告'),artifactId=crypto.randomUUID(),input={artifactId,name:'report.md',sizeBytes:bytes.length,sha256:await sha256Hex(bytes)};await expect(bridgeInput(env,r,crypto.randomUUID())).rejects.toMatchObject({code:'PERMISSION_DENIED'});await expect(bridgeArtifactInit(env,r,{...input,name:'../private.md'})).rejects.toMatchObject({code:'VALIDATION_FAILED'});const a=await bridgeArtifactInit(env,r,input);await expect(completeBridgeHandoff(env,r,{summary:'完成分析',artifactIds:[artifactId],sessionId:'session-1'})).rejects.toMatchObject({code:'INVALID_STATE'});await expect(storeBridgeArtifact(env,r,artifactId,new TextEncoder().encode('wrong'))).rejects.toMatchObject({code:'VALIDATION_FAILED'});await storeBridgeArtifact(env,r,artifactId,bytes);await storeBridgeArtifact(env,r,artifactId,bytes);expect(await bridgeArtifactInit(env,r,input)).toMatchObject({fileId:a.fileId,stored:true});const h=await completeBridgeHandoff(env,r,{summary:'完成分析',artifactIds:[artifactId],sessionId:'session-1'});expect(h.state).toBe('ready_for_review');expect(await env.DB.prepare('SELECT revision,lifecycle_state FROM tasks WHERE id=?1').bind(f.taskId).first()).toMatchObject({revision:1,lifecycle_state:'in_progress'});expect(await env.DB.prepare('SELECT COUNT(*) n FROM jobs WHERE kind!=\'agent_run\' AND project_id=?1').bind(f.projectId).first()).toMatchObject({n:0});});
 it('adopts once using normal submission and rejects changed basis',async()=>{const f=await fixture(),r=await running(f);await completeBridgeHandoff(env,r,{summary:'成果结论',artifactIds:[],sessionId:'session-1'});await env.DB.prepare('UPDATE ai_config_versions SET enabled=0').run();const finished=await loadBridgeHandoff(env,r.id),s=await adoptBridgeResult(env,finished,f.user.userId,1);expect(s).toMatchObject({taskId:f.taskId,status:'pending',body:'成果结论'});const again=await adoptBridgeResult(env,await loadBridgeHandoff(env,r.id),f.user.userId,1);expect(again.submissionId).toBe(s.submissionId);expect(await env.DB.prepare("SELECT COUNT(*) n FROM material_versions WHERE project_id=?1 AND origin='ai_adoption'").bind(f.projectId).first()).toMatchObject({n:1});expect(await env.DB.prepare('SELECT revision,lifecycle_state FROM tasks WHERE id=?1').bind(f.taskId).first()).toMatchObject({revision:2,lifecycle_state:'submitted'});
 const g=await fixture(),q=await running(g);await completeBridgeHandoff(env,q,{summary:'成果',artifactIds:[],sessionId:'session-1'});await env.DB.prepare("UPDATE project_goals SET detail='new',revision=revision+1 WHERE project_id=?1").bind(g.projectId).run();await expect(adoptBridgeResult(env,await loadBridgeHandoff(env,q.id),g.user.userId,1)).rejects.toMatchObject({code:'INVALID_STATE'});});
 it('browser routes use cookie sessions, bearer is not a generic API credential, workspace paths rejected',async()=>{const f=await fixture(),app=createApp(),request=(path:string,method='GET',body?:unknown,headers?:Record<string,string>)=>app.request(BASE+path,{method,headers:{...(body===undefined?{}:{'content-type':'application/json'}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})},env);
 expect((await request('/api/v1/agent-bridges/devices','GET',undefined,{cookie:authCookie(f.user.token)})).status).toBe(200);expect((await request('/api/v1/agent-bridges/device','GET',undefined,{authorization:'Bearer '+f.secret})).status).toBe(200);expect((await request('/api/v1/projects','GET',undefined,{authorization:'Bearer '+f.secret})).status).toBe(401);
 expect((await request('/api/v1/agent-bridges/device/workspaces','POST',{projectId:f.projectId,workspaceLabel:'C:\\private'},{authorization:'Bearer '+f.secret})).status).toBe(400);const h=await f.start();expect((await request('/api/v1/agent-bridges/handoffs/'+h.handoffId,'GET',undefined,{cookie:authCookie(f.user.token)})).status).toBe(200);
 });
 it('captures latest saved standard and atomically refuses a new standard during adoption',async()=>{
  const f=await fixture(),first=await saveStandard(env,f.projectId,f.user.userId,{requirements:[{title:'当前标准',detail:'资料须完整'}],weights:[{key:'quality',label:'质量',weight:100}]});
  const r=await running(f),snapshot=await bridgeSnapshot(env,r);expect(snapshot.inputs.find(i=>i.path==='context/standard.json')!.text).toContain(first.standardsVersionId);
  await completeBridgeHandoff(env,r,{summary:'成果',artifactIds:[],sessionId:'session-1'});
  const guarded={...env,DB:{prepare:(sql:string)=>{const statement=env.DB.prepare(sql);return statement;},batch:async(statements:D1PreparedStatement[])=>{
   if(statements.length>=6)await saveStandard(env,f.projectId,f.user.userId,{requirements:[{title:'新版标准',detail:'增加新要求'}],weights:[{key:'quality',label:'质量',weight:100}]});return env.DB.batch(statements);
  }}} as unknown as Env;
  await expect(adoptBridgeResult(guarded,await loadBridgeHandoff(env,r.id),f.user.userId,1)).rejects.toMatchObject({code:'INVALID_STATE'});
  expect(await env.DB.prepare('SELECT COUNT(*) n FROM task_submissions WHERE task_id=?1').bind(f.taskId).first()).toEqual({n:0});expect(await env.DB.prepare("SELECT COUNT(*) n FROM material_versions WHERE project_id=?1 AND origin='ai_adoption'").bind(f.projectId).first()).toEqual({n:0});
 });
 it('delegates only fixed listed inputs and refuses deleted original files',async()=>{
  const f=await fixture(),file=await createFileInit(env,{projectId:f.projectId,uploaderUserId:f.user.userId,fileName:'input.md'});await storeFileContent(env,{projectId:f.projectId,fileId:file.fileId,bytes:new TextEncoder().encode('完整原始资料')});const materialId=crypto.randomUUID(),versionId=crypto.randomUUID(),now=new Date().toISOString();
  await env.DB.batch([env.DB.prepare("INSERT INTO materials(id,project_id,title,kind,current_version_id,created_by,created_at,updated_at) VALUES(?1,?2,'材料','document',?3,?4,?5,?5)").bind(materialId,f.projectId,versionId,f.user.userId,now),env.DB.prepare("INSERT INTO material_versions(id,material_id,project_id,revision,doc_json,markdown,origin,author_id,created_at,attachments_json) VALUES(?1,?2,?3,1,'{}','完整文本','manual',?4,?5,?6)").bind(versionId,materialId,f.projectId,f.user.userId,now,JSON.stringify([{fileId:file.fileId,name:'input.md'}]))]);
  const r=await running(f),snapshot=await bridgeSnapshot(env,r);expect(snapshot.inputs.some(i=>i.text.includes('完整文本'))).toBe(true);expect(snapshot.files[0]!.fileId).toBe(file.fileId);const data=await bridgeInput(env,r,file.fileId);expect(await new Response(data.body).text()).toBe('完整原始资料');
  await env.DB.prepare('UPDATE files SET deleted_at=?2,lifecycle_version=lifecycle_version+1 WHERE id=?1').bind(file.fileId,now).run();await expect(bridgeInput(env,r,file.fileId)).rejects.toMatchObject({code:'INVALID_STATE'});expect((await refreshBridgeHandoff(env,r)).stale).toBe(1);
 });
 it('rechecks device capability atomically after caller obtained a run',async()=>{const f=await fixture(),r=await running(f);await env.DB.prepare('UPDATE agent_bridge_devices SET revoked_at=?2 WHERE id=?1').bind(f.device.id,new Date().toISOString()).run();await expect(recordBridgeEvent(env,r,{sequence:3,type:'running',sessionId:'session-1'})).rejects.toMatchObject({code:'INVALID_STATE'});await expect(completeBridgeHandoff(env,r,{summary:'成果',artifactIds:[],sessionId:'session-1'})).rejects.toMatchObject({code:'INVALID_STATE'});expect(await loadBridgeHandoff(env,r.id)).toMatchObject({state:'running',last_sequence:2});});
 it('keeps referenced immutable snapshots and collects only orphan bridge snapshots',async()=>{const f=await fixture(),r=await ready(f),orphan=`agent-bridges/${f.projectId}/${crypto.randomUUID()}/snapshot-${'a'.repeat(64)}.json`;await env.FILES.put(orphan,'{}');const gc=await gcOrphanObjects(env,new Date(Date.now()+86400000).toISOString(),{graceDays:0});expect(gc.deleted).toContain(orphan);expect(gc.deleted).not.toContain(r.snapshot_key);expect(await env.FILES.get(r.snapshot_key!)).not.toBeNull();});
 it('runs the authenticated public API from pairing through upload and reviewed adoption',async()=>{
  const f=await fixture(),app=createApp(),secret=crypto.randomUUID()+crypto.randomUUID(),cookie={cookie:authCookie(f.user.token)},bearer={authorization:'Bearer '+secret};
  const request=async(path:string,method='GET',body?:unknown,headers:Record<string,string>={},binary=false)=>{
   const response=await app.request(BASE+'/api/v1/agent-bridges'+path,{method,headers:{...headers,...(body===undefined?{}:{'content-type':binary?'application/octet-stream':'application/json'})},...(body===undefined?{}:{body:binary?body as Uint8Array:JSON.stringify(body)})},offline);
   return{status:response.status,payload:await response.json() as {data:Record<string,unknown>;error?:{code:string}}};
  };
  const paired=await request('/pairings','POST',{credentialHash:await sha256Hex(secret),deviceName:'NewDesktop',bridgeVersion:'0.1.0',dshVersion:'0.2.0-rc.2'});expect(paired.status).toBe(200);const deviceId=paired.payload.data.pairingId as string;expect(paired.payload.data.approvalUrl).toContain('/app/agent-bridges/connect?pairing='+deviceId);
  const pending=await request('/pairings/'+deviceId,'GET',undefined,cookie);expect(pending.payload.data).toMatchObject({status:'pending',projects:[{projectId:f.projectId}]});expect((await request('/pairings/'+deviceId+'/approve','POST',{projectIds:[f.projectId]},cookie)).status).toBe(200);
  expect((await request('/device/workspaces','POST',{projectId:f.projectId,workspaceLabel:'Office'},bearer)).status).toBe(200);expect((await request('/device/heartbeat','POST',{},bearer)).status).toBe(200);
  const path=`/projects/${f.projectId}/tasks/${f.taskId}/handoffs`,idem={'idempotency-key':crypto.randomUUID()},created=await request(path,'POST',{expectedRevision:1,targetDeviceId:deviceId},{...cookie,...idem});expect(created.status).toBe(202);const handoffId=created.payload.data.handoffId as string;expect(created.payload.data.state).toBe('checking');
  const job=await env.DB.prepare('SELECT job_id FROM task_agent_eligibility WHERE task_id=?1').bind(f.taskId).first<{job_id:string}>();vi.stubGlobal('fetch',vi.fn(async(url:RequestInfo|URL,init?:RequestInit)=>{assertGoRequest(url,init);return new Response(JSON.stringify({choices:[{message:{content:'{"eligible":true,"reason":"可完成数字资料分析"}'}}],usage:{prompt_tokens:30,completion_tokens:20}}),{headers:{'content-type':'application/json'}});}));await runAiJob(env,job!.job_id);
  const claimed=await request('/device/claim','POST',{},bearer);expect(claimed.status).toBe(200);expect(claimed.payload.data.handoff).toMatchObject({handoffId,state:'claimed'});
  const snapshot=await request(`/handoffs/${handoffId}/snapshot`,'GET',undefined,bearer);expect(snapshot.status).toBe(200);expect(snapshot.payload.data.prompt).toContain('team_office_complete');expect(snapshot.payload.data.prompt).not.toContain('bridge_register_result');expect(snapshot.payload.data.artifactPolicy).toMatchObject({maxFileBytes:52428800,maxArtifacts:20});
  expect((await request(`/handoffs/${handoffId}/events`,'POST',{sequence:1,type:'session_created',sessionId:'api-session'},bearer)).status).toBe(200);expect((await request(`/handoffs/${handoffId}/events`,'POST',{sequence:2,type:'prompt_accepted',sessionId:'api-session'},bearer)).status).toBe(200);
  const bytes=new TextEncoder().encode('API验证成果'),artifactId=crypto.randomUUID(),artifactBody={artifactId,name:'api-report.md',sizeBytes:bytes.length,sha256:await sha256Hex(bytes)};
  expect((await request(`/handoffs/${handoffId}/artifacts`,'POST',artifactBody,bearer)).status).toBe(200);expect((await request(`/handoffs/${handoffId}/artifacts/${artifactId}/content`,'PUT',bytes,bearer,true)).status).toBe(200);const done=await request(`/handoffs/${handoffId}/complete`,'POST',{summary:'API验证结果',artifactIds:[artifactId],sessionId:'api-session'},bearer);expect(done.status).toBe(200);expect(done.payload.data).toMatchObject({state:'ready_for_review',stale:false});
  expect((await request(`/handoffs/${handoffId}/adopt-and-submit`,'POST',{expectedTaskRevision:1,reviewed:true},bearer)).status).toBe(401);
  await env.DB.prepare('UPDATE ai_config_versions SET enabled=0').run();const adopted=await request(`/handoffs/${handoffId}/adopt-and-submit`,'POST',{expectedTaskRevision:1,reviewed:true},cookie);expect(adopted.status).toBe(200);expect(adopted.payload.data).toMatchObject({taskId:f.taskId,status:'pending'});
  const read=await request(`/handoffs/${handoffId}`,'GET',undefined,cookie);expect(read.payload.data).toMatchObject({stale:false,adoptedSubmissionId:adopted.payload.data.submissionId});
  const again=await request(`/handoffs/${handoffId}/adopt-and-submit`,'POST',{expectedTaskRevision:1,reviewed:true},cookie);expect(again.payload.data.submissionId).toBe(adopted.payload.data.submissionId);
  expect((await request('/devices/'+deviceId,'DELETE',undefined,cookie)).status).toBe(200);expect((await request(`/handoffs/${handoffId}/snapshot`,'GET',undefined,bearer)).status).toBe(403);
 });
 it('returns an explicit busy conflict when another member targets the same task',async()=>{const f=await fixture();await f.start();const other=await seedUser(),secret=crypto.randomUUID()+crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO project_members(id,project_id,user_id,role,joined_at) VALUES(?1,?2,?3,'member',?4)").bind(crypto.randomUUID(),f.projectId,other.userId,now).run();const pair=await createBridgePairing(env,{credentialHash:await sha256Hex(secret),deviceName:'Other',bridgeVersion:'1',dshVersion:'1'},BASE);await approveBridgePairing(env,pair.pairingId,other.userId,[f.projectId]);await env.DB.prepare("UPDATE agent_bridge_scopes SET workspace_label='OtherOffice' WHERE device_id=?1").bind(pair.pairingId).run();await expect(createBridgeHandoff(offline,f.projectId,f.taskId,other.userId,{expectedRevision:1,targetDeviceId:pair.pairingId},crypto.randomUUID())).rejects.toMatchObject({code:'INVALID_STATE',status:409,message:'任务已有未结束的本地交接'});});
 it.each(['browser_revoke','device_disconnect','member_removed','browser_cancel'])('accepts only terminal cancel ACK and releases sticky slot after %s',async change=>{
  const f=await fixture(),r=await running(f),app=createApp(),provider=vi.mocked(globalThis.fetch),cookie={cookie:authCookie(f.user.token)},bearer={authorization:'Bearer '+f.secret};
  const request=(path:string,method='GET',body?:unknown,headers:Record<string,string>=bearer)=>app.request(BASE+'/api/v1/agent-bridges'+path,{method,headers:{...headers,...(body===undefined?{}:{'content-type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})},offline);
  if(change==='browser_revoke')expect((await request('/devices/'+f.device.id,'DELETE',undefined,cookie)).status).toBe(200);
  if(change==='device_disconnect')expect((await request('/device/disconnect','POST',{})).status).toBe(200);
  if(change==='member_removed')await env.DB.prepare('DELETE FROM project_members WHERE project_id=?1 AND user_id=?2').bind(f.projectId,f.user.userId).run();
  if(change==='browser_cancel')expect((await request(`/handoffs/${r.id}/cancel`,'POST',{},cookie)).status).toBe(200);
  if(change!=='browser_cancel'){for(const path of [`/handoffs/${r.id}`,`/handoffs/${r.id}/snapshot`])expect((await request(path)).status).toBe(403);expect((await request('/device/claim','POST',{})).status).toBe(403);expect((await request(`/handoffs/${r.id}/events`,'POST',{sequence:10,type:'running',sessionId:'session-1'})).status).toBe(403);}
  const events=`/handoffs/${r.id}/events`,ack={sequence:10,type:'cancelled',sessionId:'session-1',message:'本地执行已停止'};
  expect((await request(events,'POST',{...ack,sessionId:'other-session'})).status).toBe(403);
  const first=await request(events,'POST',ack);expect(first.status).toBe(200);expect((await first.json() as {data:unknown}).data).toEqual({acknowledged:true,state:'cancelled'});
  const replay=await request(events,'POST',ack);expect(replay.status).toBe(200);expect((await replay.json() as {data:unknown}).data).toEqual({acknowledged:true,state:'cancelled'});
  expect((await request(events,'POST',{...ack,message:'不同事件'})).status).toBe(409);
  expect(await env.DB.prepare("SELECT COUNT(*) n FROM agent_bridge_handoffs WHERE task_id=?1 AND state IN ('claimed','running','waiting_input','uploading','cancel_requested','dispatch_uncertain')").bind(f.taskId).first()).toEqual({n:0});expect(provider).toHaveBeenCalledTimes(1);
  if(change==='member_removed')expect((await request(`/handoffs/${r.id}`,'GET',undefined,cookie)).status).toBe(403);
 });
 it('rate limits anonymous pairing by Cloudflare IP without model or job calls',async()=>{
  const app=createApp(),provider=vi.fn();vi.stubGlobal('fetch',provider);const ip='192.0.2.20';
  for(let n=0;n<21;n++){const secret=crypto.randomUUID()+crypto.randomUUID(),res=await app.request(BASE+'/api/v1/agent-bridges/pairings',{method:'POST',headers:{'content-type':'application/json','cf-connecting-ip':ip},body:JSON.stringify({credentialHash:await sha256Hex(secret),deviceName:'RateDesktop',bridgeVersion:'1',dshVersion:'1'})},env);expect(res.status).toBe(n<20?200:429);}
  expect(provider).not.toHaveBeenCalled();expect(await env.DB.prepare('SELECT COUNT(*) n FROM agent_bridge_devices WHERE device_name=\'RateDesktop\'').first()).toEqual({n:20});
 });
 it('blocks queued tasks in an archived project while preserving running drafts as stale',async()=>{
  const f=await fixture(),r=await ready(f);await env.DB.prepare("UPDATE projects SET status='archived' WHERE id=?1").bind(f.projectId).run();expect(await claimBridgeHandoff(env,f.device)).toBeNull();expect(await loadBridgeHandoff(env,r.id)).toMatchObject({state:'blocked',stale:1});
  const g=await fixture(),active=await running(g);await env.DB.prepare("UPDATE projects SET status='archived' WHERE id=?1").bind(g.projectId).run();const draft=await completeBridgeHandoff(env,active,{summary:'保留已完成成果',artifactIds:[],sessionId:'session-1'});expect(draft).toMatchObject({state:'ready_for_review',stale:true});
 });
});
