import { describe, expect, it } from 'vitest';
import { env, BASE } from './helpers/env';
import { seedProject, seedUser, authCookie } from './helpers/seed';
import { sha256Hex } from '../src/core/db';
import { approveBridgePairing, bridgeScopeOptions, createBridgePairing, updateBridgeScopes } from '../src/services/agent-bridges';
import { createApp } from '../src/app';
async function fixture() { const owner = await seedUser(), other = await seedUser(), first = await seedProject(owner.userId), second = await seedProject(owner.userId), foreign = await seedProject(other.userId); const pair = await createBridgePairing(env, { credentialHash: await sha256Hex(crypto.randomUUID()), deviceName: 'DSH', bridgeVersion: '0.1.0', dshVersion: '0.2.0-rc.2' }, BASE); await approveBridgePairing(env, pair.pairingId, owner.userId, [first]); await env.DB.prepare('UPDATE agent_bridge_scopes SET workspace_label=?2 WHERE device_id=?1').bind(pair.pairingId, 'Office').run(); return { owner, other, first, second, foreign, id: pair.pairingId }; }
describe('bridge settings authorization', () => {
 it('lists only owner memberships and preserves retained directory when adding projects', async () => { const f = await fixture(); const options = await bridgeScopeOptions(env, f.id, f.owner.userId); expect(options.items.map(p => p.projectId).sort()).toEqual([f.first, f.second].sort()); expect(options.items.find(p => p.projectId === f.first)?.authorized).toBe(true); const updated = await updateBridgeScopes(env, f.id, f.owner.userId, [f.first, f.second]); expect(updated.projects.find(p => p.projectId === f.first)?.workspaceLabel).toBe('Office'); expect(updated.projects.find(p => p.projectId === f.second)?.workspaceLabel).toBeNull(); await updateBridgeScopes(env, f.id, f.owner.userId, []); expect((await bridgeScopeOptions(env, f.id, f.owner.userId)).items.every(p => !p.authorized)).toBe(true); });
 it('refuses foreign owners and foreign projects without partial mutation', async () => { const f = await fixture(); await expect(updateBridgeScopes(env, f.id, f.other.userId, [f.foreign])).rejects.toMatchObject({ code: 'NOT_FOUND' }); await expect(updateBridgeScopes(env, f.id, f.owner.userId, [f.second, f.foreign])).rejects.toMatchObject({ code: 'PERMISSION_DENIED' }); const rows = (await env.DB.prepare('SELECT project_id FROM agent_bridge_scopes WHERE device_id=?1').bind(f.id).all()).results; expect(rows).toEqual([{ project_id: f.first }]); });
 it('blocks queued work atomically on project removal without erasing handoff history', async () => { const f = await fixture(), taskId = crypto.randomUUID(), runId = crypto.randomUUID(), now = new Date().toISOString(); await env.DB.prepare("INSERT INTO tasks(id,project_id,title,detail,criteria,status,lifecycle_state,revision,created_by,created_at,updated_at) VALUES(?1,?2,'任务','说明','标准','doing','in_progress',1,?3,?4,?4)").bind(taskId, f.first, f.owner.userId, now).run(); await env.DB.prepare("INSERT INTO agent_bridge_handoffs(id,project_id,task_id,task_revision,device_id,requested_by,idempotency_key,request_hash,state,created_at,updated_at,expires_at) VALUES(?1,?2,?3,1,?4,?5,?6,'hash','waiting_device',?7,?7,?7)").bind(runId, f.first, taskId, f.id, f.owner.userId, crypto.randomUUID(), now).run(); await updateBridgeScopes(env, f.id, f.owner.userId, []); expect(await env.DB.prepare('SELECT state,reason FROM agent_bridge_handoffs WHERE id=?1').bind(runId).first()).toEqual({ state: 'blocked', reason: '项目授权已撤销' }); });
 it('scope removal requests local cancellation of active work before releasing authorization', async () => { const f = await fixture(), taskId = crypto.randomUUID(), runId = crypto.randomUUID(), now = new Date().toISOString(); await env.DB.prepare("INSERT INTO tasks(id,project_id,title,detail,criteria,status,lifecycle_state,revision,created_by,created_at,updated_at) VALUES(?1,?2,'任务','说明','标准','doing','in_progress',1,?3,?4,?4)").bind(taskId, f.first, f.owner.userId, now).run(); await env.DB.prepare("INSERT INTO agent_bridge_handoffs(id,project_id,task_id,task_revision,device_id,requested_by,idempotency_key,request_hash,state,created_at,updated_at,expires_at) VALUES(?1,?2,?3,1,?4,?5,?6,'hash','running',?7,?7,?7)").bind(runId, f.first, taskId, f.id, f.owner.userId, crypto.randomUUID(), now).run(); await updateBridgeScopes(env, f.id, f.owner.userId, []); expect(await env.DB.prepare('SELECT state FROM agent_bridge_handoffs WHERE id=?1').bind(runId).first()).toEqual({ state: 'cancel_requested' }); expect((await env.DB.prepare('SELECT project_id FROM agent_bridge_scopes WHERE device_id=?1').bind(f.id).all()).results).toEqual([]); });
 it('browser route requires login and rejects device credentials for scope changes', async () => { const f = await fixture(), app = createApp(), path = BASE + '/api/v1/agent-bridges/devices/' + f.id + '/projects'; expect((await app.request(path, {}, env)).status).toBe(401); const response = await app.request(path, { method: 'POST', headers: { cookie: authCookie(f.owner.token), 'content-type': 'application/json' }, body: JSON.stringify({ projectIds: [f.second] }) }, env); expect(response.status).toBe(200); expect((await response.json() as { data: { projects: Array<{ projectId: string }> } }).data.projects.map(p => p.projectId)).toEqual([f.second]); });
});
