import {afterEach,describe,expect,it,vi} from 'vitest';
import {SELF} from 'cloudflare:test';
import {env,BASE} from './helpers/env';
import {configureGoFixture,assertGoRequest} from './helpers/provider-config';
import {seedProject,seedUser,authCookie} from './helpers/seed';
import type {Env} from '../src/env';
import {enqueueTaskAssistancePlan,readTaskAssistancePlan,runTaskAssistancePlanJob} from '../src/services/task-assistance-plan';
import {backfillTaskAgentEligibility,checkTaskAgentEligibilityAutomatically,readTaskAgentEligibility} from '../src/services/task-agent-eligibility';
import {runAiJob} from '../src/services/ai-jobs';
import {withIdempotency} from '../src/services/idempotency';
await configureGoFixture();afterEach(()=>vi.unstubAllGlobals());
const offline={...env,AGENT_WORKFLOW:{create:async()=>{throw new Error('offline fixture');}}} as unknown as Env;
async function fixture(){await env.DB.prepare('UPDATE ai_config_versions SET enabled=1').run();const user=await seedUser(),projectId=await seedProject(user.userId),taskId=crypto.randomUUID(),now=new Date().toISOString();await env.DB.batch([
 env.DB.prepare("UPDATE projects SET ai_collaboration_enabled=1,description='背景信息' WHERE id=?1").bind(projectId),
 env.DB.prepare("INSERT INTO tasks(id,project_id,title,detail,criteria,status,revision,created_by,created_at,updated_at) VALUES(?1,?2,'真人采访','去现场采访并整理','产出记录','todo',1,?3,?4,?4)").bind(taskId,projectId,user.userId,now),]);
 await env.DB.prepare('UPDATE task_agent_auto_checks SET pending=0,config_version_id=(SELECT id FROM ai_config_versions ORDER BY version DESC LIMIT 1) WHERE task_id!=?1').bind(taskId).run();
 return{user,projectId,taskId,start:(regenerate=false,revision=1)=>enqueueTaskAssistancePlan(offline,projectId,taskId,user.userId,revision,regenerate),read:()=>readTaskAssistancePlan(env,projectId,taskId,user.userId)};}
function model(markdown:unknown='## 实施步骤 人工采访；所需资料 提纲；人工环节 到场；验收检查 记录完整',before?:()=>Promise<void>){const provider=vi.fn(async(url:RequestInfo|URL,init?:RequestInit)=>{assertGoRequest(url,init);await before?.();return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({markdown})}}],usage:{prompt_tokens:30,completion_tokens:20}}),{headers:{'content-type':'application/json'}});});vi.stubGlobal('fetch',provider);return provider;}
describe('persisted manual task assistance plan',()=>{
 it('GET never generates; human tasks generate persisted plans reused on reopen',async()=>{const f=await fixture(),provider=model();expect(await f.read()).toMatchObject({status:'missing',plan:null});expect(provider).not.toHaveBeenCalled();const a=await f.start();await runAiJob(env,a.jobId!);expect(await f.read()).toMatchObject({status:'ready',plan:{stale:false,markdown:expect.stringContaining('人工采访')}});expect((await f.start()).jobId).toBe(a.jobId);expect(provider).toHaveBeenCalledTimes(1);const request=JSON.parse(String(provider.mock.calls[0]![1]?.body));expect(request.messages[1].content).toContain('背景信息');});
 it('concurrent first generations deduplicate before budget reservation',async()=>{const f=await fixture(),[a,b]=await Promise.all([f.start(),f.start()]);expect(a.jobId).toBe(b.jobId);expect(await env.DB.prepare('SELECT COUNT(*) n FROM usage_reservations WHERE project_id=?1').bind(f.projectId).first()).toMatchObject({n:1});});
 it('regeneration retains successful plan during pending and provider failure',async()=>{const f=await fixture(),a=await f.start();model('旧计划');await runAiJob(env,a.jobId!);const b=await f.start(true);expect(await f.read()).toMatchObject({status:'queued',plan:{markdown:'旧计划'}});model(null);await runAiJob(env,b.jobId!);expect(await f.read()).toMatchObject({status:'failed',plan:{markdown:'旧计划',stale:false}});});
 it.each(['title','detail','criteria'])('marks %s edits stale without automatic generation',async column=>{const f=await fixture(),a=await f.start(),provider=model();await runAiJob(env,a.jobId!);await env.DB.prepare(`UPDATE tasks SET ${column}='改变',revision=revision+1 WHERE id=?1`).bind(f.taskId).run();expect(await f.read()).toMatchObject({status:'ready',plan:{stale:true},taskRevision:2});expect(provider).toHaveBeenCalledTimes(1);});
 it('background changes reject running publication',async()=>{const f=await fixture(),a=await f.start();model('旧输入计划',async()=>{await env.DB.prepare("UPDATE projects SET description='新背景' WHERE id=?1").bind(f.projectId).run();});await runAiJob(env,a.jobId!);expect(await f.read()).toMatchObject({status:'missing',plan:null});expect(await env.DB.prepare('SELECT status FROM jobs WHERE id=?1').bind(a.jobId).first()).toMatchObject({status:'failed'});});
 it('disabled AI preserves readable successful plan without another call',async()=>{const f=await fixture(),a=await f.start(),provider=model('保留计划');await runAiJob(env,a.jobId!);await env.DB.prepare('UPDATE ai_config_versions SET enabled=0').run();expect(await f.start(true)).toMatchObject({status:'disabled',plan:{markdown:'保留计划'}});expect(provider).toHaveBeenCalledTimes(1);});
 it('membership and revision are checked before budget; removed member prevents call',async()=>{const f=await fixture();await expect(f.start(false,2)).rejects.toMatchObject({code:'VERSION_CONFLICT'});const outsider=await seedUser();await expect(readTaskAssistancePlan(env,f.projectId,f.taskId,outsider.userId)).rejects.toMatchObject({code:'PERMISSION_DENIED'});const a=await f.start(),provider=model();await env.DB.prepare('DELETE FROM project_members WHERE project_id=?1').bind(f.projectId).run();await runAiJob(env,a.jobId!);expect(provider).not.toHaveBeenCalled();});
 it('POST requires idempotency and generic job retry refuses stale replay',async()=>{const f=await fixture();const response=await SELF.fetch(`${BASE}/api/v1/projects/${f.projectId}/collaboration/tasks/${f.taskId}/assistance-plan`,{method:'POST',headers:{cookie:authCookie(f.user.token),'content-type':'application/json'},body:JSON.stringify({expectedRevision:1})});expect(response.status).toBe(400);const a=await f.start();model(null);await runAiJob(env,a.jobId!);const retry=await SELF.fetch(`${BASE}/api/v1/jobs/${a.jobId}/retry`,{method:'POST',headers:{cookie:authCookie(f.user.token)}});expect(retry.status).toBe(409);});
 it('same-key regeneration replays one job even after generation succeeds',async()=>{const f=await fixture(),key=crypto.randomUUID();const request=()=>withIdempotency(offline,{required:true,key,userId:f.user.userId,operation:'collaboration.assistance-plan',rawBody:JSON.stringify({projectId:f.projectId,taskId:f.taskId,expectedRevision:1,regenerate:true})},async()=>({status:200 as const,body:await f.start(true)}));const a=await request();model();await runAiJob(env,a.body.jobId!);const b=await request();expect(b.replayed).toBe(true);expect(b.body.jobId).toBe(a.body.jobId);expect(await env.DB.prepare('SELECT COUNT(*) n FROM jobs WHERE project_id=?1').bind(f.projectId).first()).toMatchObject({n:1});});
 it('material current versions invalidate cached plans',async()=>{const f=await fixture(),a=await f.start();model();await runAiJob(env,a.jobId!);const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO materials(id,project_id,title,kind,created_by,created_at,updated_at) VALUES(?1,?2,'新材料','document',?3,?4,?4)").bind(id,f.projectId,f.user.userId,now).run();expect(await f.read()).toMatchObject({status:'ready',plan:{stale:true}});});
 it('new active standards invalidate absent-standard context without generating automatically',async()=>{const f=await fixture(),a=await f.start();model();await runAiJob(env,a.jobId!);const rubricId=crypto.randomUUID(),standardId=crypto.randomUUID(),now=new Date().toISOString();await env.DB.batch([env.DB.prepare("INSERT INTO rubric_versions(id,project_id,version,status,weights_json,source,created_at) VALUES(?1,?2,1,'draft','{}','custom',?3)").bind(rubricId,f.projectId,now),env.DB.prepare("INSERT INTO standards_versions(id,project_id,version,title,rubric_version_id,created_at,updated_at) VALUES(?1,?2,1,'新标准',?3,?4,?4)").bind(standardId,f.projectId,rubricId,now)]);expect(await f.read()).toMatchObject({status:'ready',plan:{stale:true}});});
 it('atomic publication guards edit after final check',async()=>{const f=await fixture(),a=await f.start();model();const guarded={...env,DB:{prepare:(sql:string)=>{const statement=env.DB.prepare(sql);if(!sql.startsWith('UPDATE task_assistance_plans SET markdown='))return statement;return{bind:(...args:unknown[])=>{const bound=statement.bind(...args);return{first:()=>bound.first(),all:()=>bound.all(),run:async()=>{if(sql.startsWith('UPDATE task_assistance_plans SET markdown='))await env.DB.prepare("UPDATE tasks SET criteria='新标准' WHERE id=?1").bind(f.taskId).run();return bound.run();}};}};},batch:(stmts:D1PreparedStatement[])=>env.DB.batch(stmts)}} as unknown as Env;await runTaskAssistancePlanJob(guarded,a.jobId!);expect(await env.DB.prepare('SELECT markdown,status FROM task_assistance_plans WHERE task_id=?1').bind(f.taskId).first()).toMatchObject({markdown:null,status:'failed'});});
});
describe('automatic semantic eligibility queue',()=>{
 it('creation queues durably; unrelated status changes reuse semantic checks',async()=>{const f=await fixture();expect(await env.DB.prepare('SELECT pending FROM task_agent_auto_checks WHERE task_id=?1').bind(f.taskId).first()).toMatchObject({pending:1});await checkTaskAgentEligibilityAutomatically(offline,f.projectId,f.taskId);const a=await readTaskAgentEligibility(env,f.projectId,f.taskId,f.user.userId);expect(a.status).toBe('queued');await env.DB.prepare("UPDATE tasks SET status='doing',revision=2 WHERE id=?1").bind(f.taskId).run();expect(await env.DB.prepare('SELECT pending FROM task_agent_auto_checks WHERE task_id=?1').bind(f.taskId).first()).toMatchObject({pending:0});await checkTaskAgentEligibilityAutomatically(offline,f.projectId,f.taskId);expect((await readTaskAgentEligibility(env,f.projectId,f.taskId,f.user.userId)).jobId).toBe(a.jobId);});
 it('semantic edits queue a new check; terminal failure is not automatically replayed',async()=>{const f=await fixture();await checkTaskAgentEligibilityAutomatically(offline,f.projectId,f.taskId);const a=await readTaskAgentEligibility(env,f.projectId,f.taskId,f.user.userId);model(null);await runAiJob(env,a.jobId!);await checkTaskAgentEligibilityAutomatically(offline,f.projectId,f.taskId);expect((await readTaskAgentEligibility(env,f.projectId,f.taskId,f.user.userId)).jobId).toBe(a.jobId);await env.DB.prepare("UPDATE tasks SET detail='数字分析',revision=2 WHERE id=?1").bind(f.taskId).run();expect(await env.DB.prepare('SELECT pending FROM task_agent_auto_checks WHERE task_id=?1').bind(f.taskId).first()).toMatchObject({pending:1});await checkTaskAgentEligibilityAutomatically(offline,f.projectId,f.taskId);expect((await readTaskAgentEligibility(env,f.projectId,f.taskId,f.user.userId)).jobId).not.toBe(a.jobId);});
 it('disabled project is skipped and enabling drains missing tasks',async()=>{const f=await fixture();await env.DB.prepare('UPDATE projects SET ai_collaboration_enabled=0 WHERE id=?1').bind(f.projectId).run();await backfillTaskAgentEligibility(offline,1);expect(await env.DB.prepare('SELECT COUNT(*) n FROM jobs WHERE project_id=?1').bind(f.projectId).first()).toMatchObject({n:0});await env.DB.prepare('UPDATE projects SET ai_collaboration_enabled=1 WHERE id=?1').bind(f.projectId).run();await backfillTaskAgentEligibility(offline,1);expect((await readTaskAgentEligibility(env,f.projectId,f.taskId,f.user.userId)).status).toBe('queued');});
 it.each(['project','global'])('a new %s activation cycle resumes checks interrupted by disabling AI',async scope=>{const f=await fixture();await checkTaskAgentEligibilityAutomatically(offline,f.projectId,f.taskId);const a=await readTaskAgentEligibility(env,f.projectId,f.taskId,f.user.userId);const disable=async()=>{if(scope==='project')await env.DB.prepare('UPDATE projects SET ai_collaboration_enabled=0 WHERE id=?1').bind(f.projectId).run();else await env.DB.prepare('UPDATE ai_config_versions SET enabled=0 WHERE version=(SELECT MAX(version) FROM ai_config_versions)').run();};model('ignored',disable);await runAiJob(env,a.jobId!);expect(await env.DB.prepare('SELECT status FROM task_agent_eligibility WHERE job_id=?1').bind(a.jobId).first()).toMatchObject({status:'failed'});if(scope==='project')await env.DB.prepare('UPDATE projects SET ai_collaboration_enabled=1 WHERE id=?1').bind(f.projectId).run();else await env.DB.prepare('UPDATE ai_config_versions SET enabled=1 WHERE version=(SELECT MAX(version) FROM ai_config_versions)').run();await backfillTaskAgentEligibility(offline,25);const b=await readTaskAgentEligibility(env,f.projectId,f.taskId,f.user.userId);expect(b.jobId).not.toBe(a.jobId);expect(b.status).toBe('queued');expect(b.sourceHash).not.toBe(a.sourceHash);await backfillTaskAgentEligibility(offline,25);expect((await readTaskAgentEligibility(env,f.projectId,f.taskId,f.user.userId)).jobId).toBe(b.jobId);});
});
