import { expect,it } from 'vitest';
import { createApp } from '../src/app';
import { env,BASE } from './helpers/env';
import { seedUser,seedProject,authCookie } from './helpers/seed';
import { configureGoFixture } from './helpers/provider-config';
import { newId,nowIso } from '../src/core/db';
import { enqueueAdminAiRetries,readAdminAiRetries,recoverAdminAiRetries,retryFailedAiJob } from '../src/services/admin-ai-retries';
await configureGoFixture();
async function failed(){const user=await seedUser(),projectId=await seedProject(user.userId),id=newId(),now=nowIso();const config=await env.DB.prepare('SELECT id FROM ai_config_versions ORDER BY version DESC LIMIT 1').first<{id:string}>();await env.DB.prepare("INSERT INTO jobs(id,project_id,kind,status,input_json,created_by,created_at,updated_at) VALUES(?1,?2,'assignment_suggest','failed',?3,?4,?5,?5)").bind(id,projectId,JSON.stringify({projectId,requestedBy:user.userId,configVersionId:config!.id,secretPrompt:'must-not-be-exposed'}),user.userId,now).run();return {user,projectId,id,now};}
it('snapshots once, limits consumption, never returns prompt and does not directly call a model',async()=>{const f=await failed(),key=newId();const first=await enqueueAdminAiRetries(env,key,f.user.userId),again=await enqueueAdminAiRetries(env,key,f.user.userId);expect(again.batch.batchId).toBe(first.batch.batchId);expect(first.batch.pending).toBeGreaterThan(0);expect(JSON.stringify(await readAdminAiRetries(env))).not.toContain('must-not-be-exposed');await recoverAdminAiRetries(env,1);const linked=await env.DB.prepare('SELECT retry_job_id FROM admin_ai_retry_links WHERE parent_job_id=?1').bind(f.id).first<{retry_job_id:string}>();expect(linked).not.toBeNull();expect((await env.DB.prepare('SELECT status FROM jobs WHERE id=?1').bind(f.id).first<{status:string}>())!.status).toBe('failed');expect((await env.DB.prepare('SELECT status FROM jobs WHERE id=?1').bind(linked!.retry_job_id).first<{status:string}>())!.status).toBe('queued');expect((await retryFailedAiJob(env,f.id)).status).toBe('skipped');});
it('revoked original member and changed failure snapshots cannot be resurrected',async()=>{const f=await failed();await env.DB.prepare('DELETE FROM project_members WHERE project_id=?1 AND user_id=?2').bind(f.projectId,f.user.userId).run();expect((await retryFailedAiJob(env,f.id)).status).toBe('skipped');const next=await failed();expect((await retryFailedAiJob(env,next.id,'stale-timestamp')).status).toBe('skipped');await env.DB.prepare("UPDATE jobs SET status='cancelled' WHERE id=?1").bind(next.id).run();expect((await retryFailedAiJob(env,next.id)).status).toBe('skipped');});
it('concurrent recovery makes at most one replacement and inherits automatic chain id',async()=>{const f=await failed(),root=newId();const results=await Promise.allSettled([retryFailedAiJob(env,f.id,undefined,root),retryFailedAiJob(env,f.id,undefined,root)]);expect(results.filter(r=>r.status==='fulfilled'&&r.value.status==='queued')).toHaveLength(1);const row=await env.DB.prepare('SELECT j.input_json FROM jobs j JOIN admin_ai_retry_links l ON l.retry_job_id=j.id WHERE l.parent_job_id=?1').bind(f.id).first<{input_json:string}>();expect(JSON.parse(row!.input_json).autoRetryRootId).toBe(root);});
it('admin can read but only super-admin or operator can queue, invalid bodies rejected',async()=>{const user=await seedUser();await env.DB.prepare("UPDATE auth_accounts SET is_admin=1,account_role='admin' WHERE user_id=?1").bind(user.userId).run();const app=createApp(),url=BASE+'/api/v1/admin/ai-retries',headers={cookie:authCookie(user.token),'content-type':'application/json'};expect((await app.fetch(new Request(url,{headers}),env)).status).toBe(200);expect((await app.fetch(new Request(url,{method:'POST',headers,body:JSON.stringify({idempotencyKey:newId()})}),env)).status).toBe(403);expect((await app.fetch(new Request(url,{method:'POST',headers:{authorization:'Bearer test-admin-token','content-type':'application/json'},body:'{"idempotencyKey":"bad"}'}),env)).status).toBe(400);});
it('a skipped failure can join a new manual batch after its account is repaired',async()=>{const f=await failed();await env.DB.prepare('UPDATE auth_accounts SET password_hash=NULL WHERE user_id=?1').bind(f.user.userId).run();await enqueueAdminAiRetries(env,newId(),f.user.userId);await recoverAdminAiRetries(env,100);expect((await readAdminAiRetries(env)).activeBatch).toBeNull();await env.DB.prepare("UPDATE auth_accounts SET password_hash='restored-fixture' WHERE user_id=?1").bind(f.user.userId).run();const second=await enqueueAdminAiRetries(env,newId(),f.user.userId);expect(second.batch.pending).toBeGreaterThan(0);await recoverAdminAiRetries(env,100);expect(await env.DB.prepare('SELECT 1 FROM admin_ai_retry_links WHERE parent_job_id=?1').bind(f.id).first()).not.toBeNull();});
it('restores a failed agent run and atomically moves its current pointer, excluding adopted runs',async()=>{const f=await failed(),runId=newId();await env.DB.prepare("INSERT INTO agent_runs(id,project_id,capability,job_id,mode,status,created_at) VALUES(?1,?2,'guide',?3,'assist','failed',?4)").bind(runId,f.projectId,f.id,f.now).run();const job=await env.DB.prepare('SELECT input_json FROM jobs WHERE id=?1').bind(f.id).first<{input_json:string}>();await env.DB.prepare("UPDATE jobs SET kind='agent_run',input_json=?2 WHERE id=?1").bind(f.id,JSON.stringify({...JSON.parse(job!.input_json),runId})).run();const retry=await retryFailedAiJob(env,f.id);expect(retry.status).toBe('queued');expect(await env.DB.prepare('SELECT job_id,status FROM agent_runs WHERE id=?1').bind(runId).first()).toEqual({job_id:retry.jobId,status:'running'});await env.DB.prepare("UPDATE jobs SET status='failed' WHERE id=?1").bind(retry.jobId!).run();await env.DB.prepare("UPDATE agent_runs SET status='adopted' WHERE id=?1").bind(runId).run();expect((await retryFailedAiJob(env,retry.jobId!)).status).toBe('skipped');});
it('restores only the current active rehearsal owned by the original actor',async()=>{const f=await failed(),rehearsalId=newId();await env.DB.prepare("INSERT INTO rehearsals(id,project_id,scope,created_by,created_at,processing_job_id) VALUES(?1,?2,'all',?3,?4,?5)").bind(rehearsalId,f.projectId,f.user.userId,f.now,f.id).run();const job=await env.DB.prepare('SELECT input_json FROM jobs WHERE id=?1').bind(f.id).first<{input_json:string}>();await env.DB.prepare("UPDATE jobs SET kind='rehearsal_turn',input_json=?2 WHERE id=?1").bind(f.id,JSON.stringify({...JSON.parse(job!.input_json),rehearsalId})).run(); // No frozen assessment means an invalid legacy rehearsal must be skipped.
 expect((await retryFailedAiJob(env,f.id)).status).toBe('skipped');await env.DB.prepare("UPDATE rehearsals SET status='finished' WHERE id=?1").bind(rehearsalId).run();expect((await retryFailedAiJob(env,f.id)).status).toBe('skipped');});
it('a failed review replacement restores pending state and preserves the original actor',async()=>{const f=await failed();const {saveStandard}=await import('../src/services/project-simplification');const standard=await saveStandard(env,f.projectId,f.user.userId,{title:'test',requirements:[{title:'deliverable',detail:'evidence'}],weights:[{key:'q',label:'quality',weight:100}]});const snapshot=await env.DB.prepare('SELECT rubric_version_id,requirement_set_ids_json FROM standards_versions WHERE id=?1').bind(standard.standardsVersionId).first<{rubric_version_id:string;requirement_set_ids_json:string}>();const reviewId=newId();await env.DB.prepare("INSERT INTO reviews(id,project_id,requirement_set_id,rubric_version_id,material_version_ids_json,status,job_id,created_by,created_at) VALUES(?1,?2,?3,?4,'[]','failed',?5,?6,?7)").bind(reviewId,f.projectId,JSON.parse(snapshot!.requirement_set_ids_json)[0],snapshot!.rubric_version_id,f.id,f.user.userId,f.now).run();const input=await env.DB.prepare('SELECT input_json FROM jobs WHERE id=?1').bind(f.id).first<{input_json:string}>();await env.DB.prepare("UPDATE jobs SET kind='review_run',input_json=?2 WHERE id=?1").bind(f.id,JSON.stringify({...JSON.parse(input!.input_json),reviewId,standardsVersionId:standard.standardsVersionId})).run();const retried=await retryFailedAiJob(env,f.id);expect(retried.status).toBe('queued');expect(await env.DB.prepare('SELECT status,job_id,created_by FROM reviews WHERE id=?1').bind(reviewId).first()).toEqual({status:'pending',job_id:retried.jobId,created_by:f.user.userId});});
