import { expect,it } from 'vitest';
import { SELF } from 'cloudflare:test';
import { env,BASE } from './helpers/env';
import { configureGoFixture } from './helpers/provider-config';
import { aiConfigSchema,loadAiConfig,resolveAiConfig } from '../src/ai/config';
import { whisperEnabled } from '../src/services/audio-pipeline';
import { unseal } from '../src/ai/secrets';
import { DEFAULT_AUDIO_FILE_TRANSCRIPTION,normalizeProcessingStrategies,realtimeTranscriptionGatewayUrl } from '../../shared/audio-settings';
await configureGoFixture();
const headers={authorization:'Bearer test-admin-token','content-type':'application/json'};
async function read(){const r=await SELF.fetch(BASE+'/api/v1/admin/ai-config',{headers});expect(r.status).toBe(200);return (await r.json() as any).data;}
async function save(extra:Record<string,unknown>){const current=await read();return SELF.fetch(BASE+'/api/v1/admin/ai-config',{method:'PUT',headers,body:JSON.stringify({textEconomy:current.config.textEconomy,visionEconomy:current.config.visionEconomy,review:current.config.review,expectedVersion:current.version,...extra})});}
it('legacy configs normalize defaults while frozen strategy retains its semantics',async()=>{const current=await loadAiConfig(env.DB);expect(current!.config.audioFileTranscription).toEqual(DEFAULT_AUDIO_FILE_TRANSCRIPTION);expect(current!.config.processingStrategies).toEqual({audioFiles:'whisper-first',rehearsal:'text'});const raw=await env.DB.prepare('SELECT config_json FROM ai_config_versions WHERE id=?1').bind(current!.id).first<{config_json:string}>();const old={...JSON.parse(raw!.config_json),audioProcessingStrategy:'gemini-only'};delete old.processingStrategies;await env.DB.prepare('UPDATE ai_config_versions SET config_json=?2 WHERE id=?1').bind(current!.id,JSON.stringify(old)).run();expect((await loadAiConfig(env.DB,current!.id))!.config.processingStrategies!.audioFiles).toBe('media-only');expect(whisperEnabled({...env,AI:{}} as any,(await loadAiConfig(env.DB,current!.id))!,'audio/wav')).toBe(false);expect(normalizeProcessingStrategies({audioFiles:'whisper-first',rehearsal:'text'},'gemini-only').audioFiles).toBe('whisper-first');});
it('validates immutable file provider, processing roles and a gateway-only incomplete live draft',async()=>{expect((await save({audioFileTranscription:{provider:'google-ai-studio',model:'gemini'}})).status).toBe(400);expect((await save({processingStrategies:{audioFiles:'gemini-only',rehearsal:'text'}})).status).toBe(400);expect((await save({realtimeAudioTranscription:{provider:'google-ai-studio',model:'gemini-3.5-transcribe-live',gatewayId:'',apiUrl:'https://google.example'}})).status).toBe(400);expect((await save({realtimeAudioTranscription:{provider:'google-ai-studio',model:'gemini-3.5-transcribe-live',gatewayId:'UPPER'}})).status).toBe(400);expect((await save({realtimeAudioTranscription:{provider:'google-ai-studio',model:'gemini-3.5-transcribe-live',gatewayId:''},processingStrategies:{audioFiles:'media-only',rehearsal:'voice-with-text-fallback'}})).status).toBe(201);const saved=await read();expect(saved.config.realtimeAudioTranscription.keyConfigured).toBe(false);expect(saved.config.processingStrategies.rehearsal).toBe('voice-with-text-fallback');});
it('isolates live credentials, seals both, redacts GET and retains/clears them independently',async()=>{const realtime={provider:'google-ai-studio',model:'gemini-3.5-transcribe-live',gatewayId:'live-gateway',languageCodes:['zh-CN']};expect((await save({realtimeAudioTranscription:{...realtime,apiKey:'live-private-key',gatewayToken:'gateway-private-token'}})).status).toBe(201);let loaded=(await loadAiConfig(env.DB))!;expect(await unseal(loaded.config.realtimeAudioTranscription!.apiKeyEncrypted!,env.AUTH_SECRET)).toBe('live-private-key');expect(await unseal(loaded.config.realtimeAudioTranscription!.gatewayTokenEncrypted!,env.AUTH_SECRET)).toBe('gateway-private-token');expect(JSON.stringify((await read()).config)).not.toMatch(/live-private-key|gateway-private-token|apiKeyEncrypted|gatewayTokenEncrypted/);const cipher=loaded.config.realtimeAudioTranscription!.apiKeyEncrypted;expect((await save({realtimeAudioTranscription:realtime})).status).toBe(201);loaded=(await loadAiConfig(env.DB))!;expect(loaded.config.realtimeAudioTranscription!.apiKeyEncrypted).toBe(cipher);expect((await save({realtimeAudioTranscription:{...realtime,clearKey:true}})).status).toBe(201);loaded=(await loadAiConfig(env.DB))!;expect(loaded.config.realtimeAudioTranscription!.apiKeyEncrypted).toBeUndefined();expect(loaded.config.realtimeAudioTranscription!.gatewayTokenEncrypted).toBeDefined();expect((await save({realtimeAudioTranscription:{...realtime,clearGatewayToken:true}})).status).toBe(201);expect((await read()).config.realtimeAudioTranscription.gatewayTokenConfigured).toBe(false);expect((await save({clearRealtimeAudioTranscription:true})).status).toBe(201);expect((await read()).config.realtimeAudioTranscription).toBeUndefined();});
it('new strategies take precedence, omitted settings retain, and legacy-only saves still switch audio files',async()=>{expect((await save({audioProcessingStrategy:'gemini-only',processingStrategies:{audioFiles:'whisper-first',rehearsal:'voice-with-text-fallback'}})).status).toBe(201);let loaded=(await loadAiConfig(env.DB))!;expect(loaded.config.audioProcessingStrategy).toBe('whisper-first');expect(whisperEnabled({...env,AI:{}} as any,loaded,'audio/wav')).toBe(true);expect((await save({})).status).toBe(201);expect((await read()).config.processingStrategies.rehearsal).toBe('voice-with-text-fallback');expect((await save({audioProcessingStrategy:'gemini-only'})).status).toBe(201);expect((await read()).config.processingStrategies.audioFiles).toBe('media-only');});
it('audio-only changes retain enabled text routing and never borrow media credentials',async()=>{await env.DB.prepare('UPDATE ai_config_versions SET enabled=1').run();expect((await save({realtimeAudioTranscription:{provider:'google-ai-studio',model:'gemini-3.5-transcribe-live',gatewayId:'separate'},processingStrategies:{audioFiles:'media-only',rehearsal:'voice-with-text-fallback'}})).status).toBe(201);const current=await read();expect(current.enabled).toBe(true);expect(current.config.realtimeAudioTranscription.keyConfigured).toBe(false);const loaded=(await loadAiConfig(env.DB))!;const resolved=resolveAiConfig(aiConfigSchema.parse({...loaded.config,routingMode:'unified',unified:loaded.config.textEconomy}));expect(resolved.realtimeAudioTranscription).toEqual(loaded.config.realtimeAudioTranscription);expect(resolved.audioFileTranscription).toEqual(DEFAULT_AUDIO_FILE_TRANSCRIPTION);});
it('gateway route accepts only fixed account and gateway bindings',()=>{expect(realtimeTranscriptionGatewayUrl('bound-account','voice-gateway')).toBe('wss://gateway.ai.cloudflare.com/v1/bound-account/voice-gateway/google');expect(()=>realtimeTranscriptionGatewayUrl('https://google.example','voice-gateway')).toThrow();expect(()=>realtimeTranscriptionGatewayUrl('bound-account','')).toThrow();});
it('partial audio saves preserve all core models, enabled state and independent TTS defaults',async()=>{const before=(await loadAiConfig(env.DB))!;const result=await SELF.fetch(BASE+'/api/v1/admin/ai-config',{method:'PUT',headers,body:JSON.stringify({expectedVersion:before.version,rehearsalSpeech:{model:'gemini-3.8-flash-tts',voice:'Aoede'},processingStrategies:{audioFiles:'whisper-first',rehearsal:'voice-with-text-fallback'}})});expect(result.status).toBe(201);const current=(await loadAiConfig(env.DB))!;expect(current.config.textEconomy).toEqual(before.config.textEconomy);expect(current.config.visionEconomy).toEqual(before.config.visionEconomy);expect(current.enabled).toBe(before.enabled);expect(current.config.rehearsalSpeech).toEqual({model:'gemini-3.8-flash-tts',voice:'Aoede'});expect((await save({rehearsalSpeech:{model:'gemini-3.5-transcribe-live',voice:'Kore'}})).status).toBe(400);});
it('audio-only first save cannot fabricate missing text configuration',async()=>{const saved=await env.DB.prepare('SELECT * FROM ai_config_versions').all<any>();await env.DB.prepare('DELETE FROM ai_config_versions').run();const response=await SELF.fetch(BASE+'/api/v1/admin/ai-config',{method:'PUT',headers,body:JSON.stringify({processingStrategies:{audioFiles:'whisper-first',rehearsal:'text'}})});expect(response.status).toBe(400);await env.DB.batch(saved.results.map(row=>env.DB.prepare('INSERT INTO ai_config_versions(id,version,config_json,enabled,notes,created_by,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7)').bind(row.id,row.version,row.config_json,row.enabled,row.notes,row.created_by,row.created_at)));});
it('audio-only versioning retains verified text probes so a later activation does not require re-probing',async()=>{const latest=(await loadAiConfig(env.DB))!;await env.DB.batch(['textEconomy','visionEconomy','review'].map(purpose=>env.DB.prepare("INSERT OR REPLACE INTO ai_probes(config_version_id,purpose,passed,report_json,tested_at) VALUES(?1,?2,1,?3,?4)").bind(latest.id,purpose,JSON.stringify({configVersion:latest.version,passed:true}),new Date().toISOString())));expect((await save({rehearsalSpeech:{model:'gemini-3.8-flash-lite-tts',voice:'Puck'}})).status).toBe(201);const after=(await loadAiConfig(env.DB))!;expect((await env.DB.prepare('SELECT COUNT(*) n FROM ai_probes WHERE config_version_id=?1 AND passed=1').bind(after.id).first<{n:number}>())!.n).toBe(3);expect((await save({enabled:true})).status).toBe(201);});
