/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=backend/wrangler.jsonc --env=production --include-runtime=false backend/cloudflare-bindings.d.ts` (hash: 41f7df98eb068cbfbd07cf711f98a188)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	DB: D1Database;
	AI: Ai;
	ENV_NAME: "production";
	MEDIA_FETCH_BASE_URL: "https://greenbp-team-office-backend.hddhp.workers.dev";
	DOCUMENT_IMPORTS_ENABLED: "true";
	RESOURCE_INDEX_ENABLED: "true";
	OCR_BATCH_ENABLED: "true";
	EMAIL_MODE: "resend";
	ALLOWED_ORIGINS: "https://team.greenbp.dpdns.org,https://greenbp-team-office.hddhp.workers.dev";
	CLOUDFLARE_ACCOUNT_ID: "17a6817bca6612a9cb11d0395eeba0ac";
	AI_GATEWAY_ID: "";
	EMAIL_FROM: "补位 AI 项目办公室 <login@auth.greenbp.dpdns.org>";
	AUTH_MODE: "password";
	EMAIL_DAILY_LIMIT: "30";
	TURNSTILE_REQUIRED: "false";
	TURNSTILE_SITE_KEY: "0x4AAAAAAFKQSg4fWagOtFAC";
	PARSE_WORKFLOW: Workflow<Parameters<import("./src/index").ParseSourceWorkflow['run']>[0]['payload']>;
	AGENT_WORKFLOW: Workflow<Parameters<import("./src/index").AgentRunWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENV_NAME" | "MEDIA_FETCH_BASE_URL" | "DOCUMENT_IMPORTS_ENABLED" | "RESOURCE_INDEX_ENABLED" | "OCR_BATCH_ENABLED" | "EMAIL_MODE" | "ALLOWED_ORIGINS" | "CLOUDFLARE_ACCOUNT_ID" | "AI_GATEWAY_ID" | "EMAIL_FROM" | "AUTH_MODE" | "EMAIL_DAILY_LIMIT" | "TURNSTILE_REQUIRED" | "TURNSTILE_SITE_KEY">> {}
}
