import { projectGoal } from './project-simplification';
import type { Env } from '../env';
import { AppError, invalidState, notFound, permissionDenied, unauthenticated, validationFailed, versionConflict } from '../core/errors';
import { newId, nowIso, sha256Hex } from '../core/db';
import { enqueueTaskAgentEligibility, readTaskAgentEligibility } from './task-agent-eligibility';
import { bridgeContextStamp, bridgeContextStampSql, buildBridgeSnapshot, type BridgeSnapshot } from './agent-bridge-context';
import { createFileInit, extOf, readFileContent, storeFileContent, uploadLimit } from './files';
import { fileTooLarge } from '../core/errors';

export type BridgeState='checking'|'waiting_device'|'claimed'|'running'|'waiting_input'|'uploading'|'ready_for_review'|'blocked'|'failed'|'cancel_requested'|'cancelled'|'dispatch_uncertain';
export type DeviceRow={id:string;owner_id:string|null;device_name:string;bridge_version:string;dsh_version:string;pairing_expires_at:string;revoked_at:string|null;last_seen_at:string|null;created_at:string};
export type BridgeResult={summary:string;artifacts:Array<{artifactId:string;fileId:string;name:string;sizeBytes:number;sha256:string}>};
export type HandoffRow={id:string;project_id:string;task_id:string;task_revision:number;device_id:string;requested_by:string;idempotency_key:string;request_hash:string;state:BridgeState;reason:string|null;snapshot_hash:string|null;snapshot_key:string|null;context_hash:string|null;context_stamp:string|null;eligibility_hash:string|null;session_id:string|null;last_sequence:number;result_json:string|null;stale:number;adopted_submission_id:string|null;created_at:string;updated_at:string;expires_at:string};
const active=['claimed','running','waiting_input','uploading','cancel_requested','dispatch_uncertain'];
const executing=['claimed','running','waiting_input','uploading'];
export const bridgeDto=(r:HandoffRow)=>({handoffId:r.id,projectId:r.project_id,taskId:r.task_id,taskRevision:r.task_revision,deviceId:r.device_id,state:r.state,reason:r.reason,snapshotHash:r.snapshot_hash,sessionId:r.session_id,result:r.result_json?JSON.parse(r.result_json) as BridgeResult:null,stale:!!r.stale,adoptedSubmissionId:r.adopted_submission_id,createdAt:r.created_at,updatedAt:r.updated_at});
/** Repeat capability checks inside the mutation, after network/R2 awaits. */
export const bridgeAuthoritySql=(h='agent_bridge_handoffs')=>`EXISTS(SELECT 1 FROM agent_bridge_devices d JOIN agent_bridge_scopes s ON s.device_id=d.id JOIN project_members m ON m.project_id=s.project_id AND m.user_id=d.owner_id WHERE d.id=${h}.device_id AND d.revoked_at IS NULL AND d.owner_id=${h}.requested_by AND s.project_id=${h}.project_id) AND EXISTS(SELECT 1 FROM project_members WHERE project_id=${h}.project_id AND user_id=${h}.requested_by)`;
export async function bridgeMember(env:Env,projectId:string,userId:string){if(!await env.DB.prepare('SELECT 1 FROM project_members WHERE project_id=?1 AND user_id=?2').bind(projectId,userId).first())throw permissionDenied('项目成员权限已失效');}
export async function loadBridgeDevice(env:Env,bearer:string|undefined):Promise<DeviceRow>{
 if(!bearer?.startsWith('Bearer ')||bearer.length<40||bearer.length>520)throw unauthenticated('设备连接凭据无效');
 const row=await env.DB.prepare('SELECT * FROM agent_bridge_devices WHERE credential_hash=?1').bind(await sha256Hex(bearer.slice(7))).first<DeviceRow>();if(!row)throw unauthenticated('设备连接凭据无效');return row;
}
export async function revokeBridgeDevice(env:Env,deviceId:string,ownerId:string|null){
 const results=await env.DB.batch([
  env.DB.prepare('UPDATE agent_bridge_devices SET revoked_at=COALESCE(revoked_at,?3) WHERE id=?1 AND owner_id IS ?2').bind(deviceId,ownerId,nowIso()),
  env.DB.prepare("UPDATE agent_bridge_handoffs SET state=CASE WHEN state IN ('checking','waiting_device') THEN 'blocked' ELSE 'cancel_requested' END,reason='设备连接已撤销',updated_at=?2 WHERE device_id=?1 AND state IN ('checking','waiting_device','claimed','running','waiting_input','uploading','dispatch_uncertain') AND EXISTS(SELECT 1 FROM agent_bridge_devices WHERE id=?1 AND owner_id IS ?3 AND revoked_at IS NOT NULL)").bind(deviceId,nowIso(),ownerId),
 ]);if(!results[0]!.meta.changes)throw notFound();return{revoked:true as const};
}
export async function requireBridgeDeviceScope(env:Env,device:DeviceRow,projectId:string){
 if(!device.owner_id||device.revoked_at)throw permissionDenied('设备未授权或连接已撤销');await bridgeMember(env,projectId,device.owner_id);
 const scope=await env.DB.prepare('SELECT workspace_label FROM agent_bridge_scopes WHERE device_id=?1 AND project_id=?2').bind(device.id,projectId).first<{workspace_label:string|null}>();if(!scope)throw permissionDenied('设备没有本项目授权');return scope;
}
export async function bridgeDeviceDto(env:Env,d:DeviceRow){const projects=d.owner_id&&!d.revoked_at?(await env.DB.prepare(`SELECT s.project_id projectId,p.name,s.workspace_label workspaceLabel FROM agent_bridge_scopes s JOIN projects p ON p.id=s.project_id JOIN project_members m ON m.project_id=p.id AND m.user_id=?2 WHERE s.device_id=?1 ORDER BY p.name,p.id`).bind(d.id,d.owner_id).all()).results:[];return{paired:!!d.owner_id,deviceId:d.id,deviceName:d.device_name,bridgeVersion:d.bridge_version,dshVersion:d.dsh_version,projects,revoked:!!d.revoked_at,lastSeenAt:d.last_seen_at,protocolVersion:1};}
/** Settings may change only this owner's current project memberships. Removal cancels work before dropping scope. */
export async function bridgeScopeOptions(env:Env,deviceId:string,userId:string){
 const d=await env.DB.prepare('SELECT * FROM agent_bridge_devices WHERE id=?1 AND owner_id=?2 AND revoked_at IS NULL').bind(deviceId,userId).first<DeviceRow>();if(!d)throw notFound();
 const items=(await env.DB.prepare('SELECT p.id projectId,p.name,EXISTS(SELECT 1 FROM agent_bridge_scopes s WHERE s.device_id=?2 AND s.project_id=p.id) authorized FROM projects p JOIN project_members m ON m.project_id=p.id WHERE m.user_id=?1 ORDER BY p.name,p.id').bind(userId,deviceId).all<{projectId:string;name:string;authorized:number}>()).results;
 return {items:items.map(p=>({...p,authorized:!!p.authorized}))};
}
export async function updateBridgeScopes(env:Env,deviceId:string,userId:string,projectIds:string[]){
 if(new Set(projectIds).size!==projectIds.length)throw validationFailed('请选择不同项目');
 await bridgeScopeOptions(env,deviceId,userId);for(const id of projectIds)await bridgeMember(env,id,userId);
 const selected=JSON.stringify(projectIds),guard=`EXISTS(SELECT 1 FROM agent_bridge_devices WHERE id=?1 AND owner_id=?2 AND revoked_at IS NULL) AND NOT EXISTS(SELECT 1 FROM json_each(?3) j WHERE NOT EXISTS(SELECT 1 FROM project_members WHERE project_id=j.value AND user_id=?2))`;
 const results=await env.DB.batch([
  env.DB.prepare(`UPDATE agent_bridge_devices SET last_seen_at=last_seen_at WHERE id=?1 AND ${guard}`).bind(deviceId,userId,selected),
  env.DB.prepare(`UPDATE agent_bridge_handoffs SET state=CASE WHEN state IN ('checking','waiting_device') THEN 'blocked' ELSE 'cancel_requested' END,reason='项目授权已撤销',updated_at=?4 WHERE device_id=?1 AND project_id NOT IN (SELECT value FROM json_each(?3)) AND state IN ('checking','waiting_device','claimed','running','waiting_input','uploading','dispatch_uncertain') AND ${guard}`).bind(deviceId,userId,selected,nowIso()),
  env.DB.prepare(`DELETE FROM agent_bridge_scopes WHERE device_id=?1 AND project_id NOT IN (SELECT value FROM json_each(?3)) AND ${guard}`).bind(deviceId,userId,selected),
  env.DB.prepare(`INSERT OR IGNORE INTO agent_bridge_scopes(device_id,project_id) SELECT ?1,value FROM json_each(?3) WHERE ${guard}`).bind(deviceId,userId,selected),
 ]);if(!results[0]!.meta.changes)throw invalidState('设备授权或项目成员权限已变化');
 return bridgeDeviceDto(env,(await env.DB.prepare('SELECT * FROM agent_bridge_devices WHERE id=?1').bind(deviceId).first<DeviceRow>())!);
}
export async function createBridgePairing(env:Env,input:{credentialHash:string;deviceName:string;bridgeVersion:string;dshVersion:string},origin:string){
 const id=newId(),now=nowIso(),expiresAt=new Date(Date.now()+600_000).toISOString();
 // Hash generation is device-owned; the cloud never receives the raw secret.
 const existing=await env.DB.prepare('SELECT * FROM agent_bridge_devices WHERE credential_hash=?1').bind(input.credentialHash).first<DeviceRow>();if(existing){if(existing.owner_id||existing.revoked_at||existing.pairing_expires_at<=now)throw invalidState('凭据已使用，请生成新的配对');return{pairingId:existing.id,approvalUrl:`${origin}/app/agent-bridges/connect?pairing=${existing.id}`,expiresAt:existing.pairing_expires_at};}
 if((await env.DB.prepare('SELECT COUNT(*) n FROM agent_bridge_devices WHERE owner_id IS NULL AND pairing_expires_at>?1').bind(now).first<{n:number}>())!.n>=1000)throw new AppError('RATE_LIMITED','等待配对设备过多，请稍后重试',429,true);
 await env.DB.prepare('INSERT INTO agent_bridge_devices(id,credential_hash,device_name,bridge_version,dsh_version,pairing_expires_at,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7)').bind(id,input.credentialHash,input.deviceName,input.bridgeVersion,input.dshVersion,expiresAt,now).run();return{pairingId:id,approvalUrl:`${origin}/app/agent-bridges/connect?pairing=${id}`,expiresAt};
}
export async function readBridgePairing(env:Env,id:string,userId:string){const d=await env.DB.prepare('SELECT * FROM agent_bridge_devices WHERE id=?1').bind(id).first<DeviceRow>();if(!d)throw notFound();if(d.owner_id&&d.owner_id!==userId)throw permissionDenied();return{pairingId:d.id,deviceName:d.device_name,bridgeVersion:d.bridge_version,dshVersion:d.dsh_version,expiresAt:d.pairing_expires_at,paired:!!d.owner_id,revoked:!!d.revoked_at};}
export async function approveBridgePairing(env:Env,id:string,userId:string,projectIds:string[]){
 if(!projectIds.length||new Set(projectIds).size!==projectIds.length)throw validationFailed('请选择不同项目');for(const p of projectIds)await bridgeMember(env,p,userId);
 const d=await env.DB.prepare('SELECT * FROM agent_bridge_devices WHERE id=?1').bind(id).first<DeviceRow>();if(!d)throw notFound();if(d.owner_id){if(d.owner_id!==userId)throw permissionDenied();return bridgeDeviceDto(env,d);}
 const result=await env.DB.batch([env.DB.prepare(`UPDATE agent_bridge_devices SET owner_id=?2 WHERE id=?1 AND owner_id IS NULL AND revoked_at IS NULL AND pairing_expires_at>?3 AND NOT EXISTS(SELECT 1 FROM json_each(?4) j WHERE NOT EXISTS(SELECT 1 FROM project_members WHERE project_id=j.value AND user_id=?2))`).bind(id,userId,nowIso(),JSON.stringify(projectIds)),...projectIds.map(p=>env.DB.prepare('INSERT OR IGNORE INTO agent_bridge_scopes(device_id,project_id) SELECT ?1,?2 WHERE EXISTS(SELECT 1 FROM agent_bridge_devices WHERE id=?1 AND owner_id=?3 AND revoked_at IS NULL)').bind(id,p,userId))]);
 if(!result[0]!.meta.changes)throw invalidState('配对已过期或成员权限已变化');return bridgeDeviceDto(env,(await env.DB.prepare('SELECT * FROM agent_bridge_devices WHERE id=?1').bind(id).first<DeviceRow>())!);
}
export async function loadBridgeHandoff(env:Env,id:string){const row=await env.DB.prepare('SELECT * FROM agent_bridge_handoffs WHERE id=?1').bind(id).first<HandoffRow>();if(!row)throw notFound('交接不存在');return row;}
export async function browserBridgeHandoff(env:Env,id:string,userId:string){const r=await loadBridgeHandoff(env,id);await bridgeMember(env,r.project_id,userId);if(r.requested_by!==userId)throw permissionDenied('仅交接发起人可访问');return r;}
export async function deviceBridgeHandoff(env:Env,id:string,d:DeviceRow){const r=await loadBridgeHandoff(env,id);if(r.device_id!==d.id)throw permissionDenied('交接不属于此设备');await requireBridgeDeviceScope(env,d,r.project_id);await bridgeMember(env,r.project_id,r.requested_by);return r;}
export async function refreshBridgeHandoff(env:Env,row:HandoffRow):Promise<HandoffRow>{
 if(!['checking','waiting_device',...active,'ready_for_review'].includes(row.state))return row;
 const current=await bridgeContextStamp(env,row.project_id,row.task_id).catch(()=>null);
 if(row.context_stamp&&current!==row.context_stamp){await env.DB.prepare(`UPDATE agent_bridge_handoffs SET stale=1,reason='任务、标准或输入资料已变化',state=CASE WHEN state IN ('checking','waiting_device') THEN 'blocked' ELSE state END,updated_at=?2 WHERE id=?1 AND adopted_submission_id IS NULL`).bind(row.id,nowIso()).run();return loadBridgeHandoff(env,row.id);}
 if(['checking','waiting_device'].includes(row.state)&&row.expires_at<=nowIso()){await env.DB.prepare("UPDATE agent_bridge_handoffs SET state='blocked',reason='等待接收已超过24小时，请重新派发',updated_at=?2 WHERE id=?1 AND state IN ('checking','waiting_device')").bind(row.id,nowIso()).run();return loadBridgeHandoff(env,row.id);}
 if(row.state==='checking'){
  let eligibility;try{eligibility=await readTaskAgentEligibility(env,row.project_id,row.task_id,row.requested_by);}catch{await env.DB.prepare("UPDATE agent_bridge_handoffs SET state='blocked',reason='任务或权限不可用',updated_at=?2 WHERE id=?1 AND state='checking'").bind(row.id,nowIso()).run();return loadBridgeHandoff(env,row.id);}
  if(eligibility.sourceHash!==row.eligibility_hash||eligibility.status==='disabled'||eligibility.status==='failed'||(eligibility.status==='ready'&&!eligibility.eligible)){await env.DB.prepare("UPDATE agent_bridge_handoffs SET state='blocked',reason=?2,updated_at=?3 WHERE id=?1 AND state='checking'").bind(row.id,eligibility.reason||'AI 适用性检查失败或配置已变化，请重新检查',nowIso()).run();}
  else if(eligibility.status==='ready'&&eligibility.eligible){try{const snapshot=await buildBridgeSnapshot(env,row.project_id,row.task_id,row.id,row.context_stamp!);const key=`agent-bridges/${row.project_id}/${row.id}/snapshot-${snapshot.snapshotHash}.json`;await env.FILES.put(key,JSON.stringify(snapshot),{httpMetadata:{contentType:'application/json'}});await env.DB.prepare(`UPDATE agent_bridge_handoffs SET state='waiting_device',snapshot_hash=?2,snapshot_key=?3,updated_at=?4 WHERE id=?1 AND state='checking' AND context_stamp=(SELECT ${bridgeContextStampSql} FROM tasks t WHERE t.id=agent_bridge_handoffs.task_id AND t.project_id=agent_bridge_handoffs.project_id AND t.archived_at IS NULL) AND EXISTS(SELECT 1 FROM task_agent_eligibility WHERE task_id=agent_bridge_handoffs.task_id AND source_hash=agent_bridge_handoffs.eligibility_hash AND status='ready' AND eligible=1)`).bind(row.id,snapshot.snapshotHash,key,nowIso()).run();}catch(e){await env.DB.prepare("UPDATE agent_bridge_handoffs SET state='blocked',reason=?2,updated_at=?3 WHERE id=?1 AND state='checking'").bind(row.id,e instanceof Error?e.message:'输入准备失败',nowIso()).run();}}
 }
 return loadBridgeHandoff(env,row.id);
}
export async function createBridgeHandoff(env:Env,projectId:string,taskId:string,userId:string,input:{expectedRevision:number;targetDeviceId:string},key:string|undefined){
 if(!key||key.length>200)throw validationFailed('请提供 Idempotency-Key');await bridgeMember(env,projectId,userId);
 const hash=await sha256Hex(JSON.stringify({projectId,taskId,...input}));const replay=await env.DB.prepare('SELECT * FROM agent_bridge_handoffs WHERE requested_by=?1 AND idempotency_key=?2').bind(userId,key).first<HandoffRow>();if(replay){if(replay.request_hash!==hash)throw new AppError('IDEMPOTENCY_CONFLICT','相同请求标识的内容不同',409,false);return bridgeDto(await refreshBridgeHandoff(env,replay));}
 const d=await env.DB.prepare('SELECT * FROM agent_bridge_devices WHERE id=?1 AND owner_id=?2 AND revoked_at IS NULL').bind(input.targetDeviceId,userId).first<DeviceRow>();if(!d)throw permissionDenied('请选择自己的已授权设备');const scope=await requireBridgeDeviceScope(env,d,projectId);if(!scope.workspace_label)throw invalidState('请先在 DSH 为项目绑定本地目录');
 const t=await env.DB.prepare('SELECT revision FROM tasks WHERE id=?1 AND project_id=?2 AND archived_at IS NULL').bind(taskId,projectId).first<{revision:number}>();if(!t)throw notFound();if(t.revision!==input.expectedRevision)throw versionConflict(t.revision);
 const existing=await env.DB.prepare("SELECT * FROM agent_bridge_handoffs WHERE task_id=?1 AND state IN ('checking','waiting_device','claimed','running','waiting_input','uploading','cancel_requested','dispatch_uncertain')").bind(taskId).first<HandoffRow>();if(existing){if(existing.requested_by!==userId||existing.device_id!==d.id)throw invalidState('任务已有未结束的本地交接');return bridgeDto(await refreshBridgeHandoff(env,existing));}
 await projectGoal(env,projectId);const stamp=await bridgeContextStamp(env,projectId,taskId),e=await readTaskAgentEligibility(env,projectId,taskId,userId),id=newId(),now=nowIso();
 await env.DB.prepare(`INSERT INTO agent_bridge_handoffs(id,project_id,task_id,task_revision,device_id,requested_by,idempotency_key,request_hash,state,context_stamp,context_hash,eligibility_hash,created_at,updated_at,expires_at)
 SELECT ?1,?2,?3,?4,?5,?6,?7,?8,'checking',?9,?10,?11,?12,?12,?13 WHERE EXISTS(SELECT 1 FROM tasks t WHERE t.id=?3 AND t.project_id=?2 AND t.revision=?4 AND t.archived_at IS NULL AND ${bridgeContextStampSql}=?9) AND EXISTS(SELECT 1 FROM agent_bridge_devices d JOIN agent_bridge_scopes s ON s.device_id=d.id JOIN project_members m ON m.project_id=s.project_id AND m.user_id=d.owner_id WHERE d.id=?5 AND d.owner_id=?6 AND d.revoked_at IS NULL AND s.project_id=?2 AND s.workspace_label IS NOT NULL) ON CONFLICT DO NOTHING`).bind(id,projectId,taskId,input.expectedRevision,d.id,userId,key,hash,stamp,await sha256Hex(stamp),e.sourceHash,now,new Date(Date.now()+86400_000).toISOString()).run();
 let row=await env.DB.prepare('SELECT * FROM agent_bridge_handoffs WHERE id=?1 OR (requested_by=?2 AND idempotency_key=?3) OR (task_id=?4 AND state IN (\'checking\',\'waiting_device\')) ORDER BY created_at LIMIT 1').bind(id,userId,key,taskId).first<HandoffRow>();if(!row||row.requested_by!==userId||row.device_id!==d.id)throw invalidState('任务或设备状态已变化');
 try{await enqueueTaskAgentEligibility(env,projectId,taskId,userId,input.expectedRevision);}catch(e){await env.DB.prepare("UPDATE agent_bridge_handoffs SET state='blocked',reason=?2,updated_at=?3 WHERE id=?1 AND state='checking'").bind(row.id,e instanceof Error?e.message:'检查未能启动',nowIso()).run();}
 row=await refreshBridgeHandoff(env,await loadBridgeHandoff(env,row.id));return bridgeDto(row);
}
export async function claimBridgeHandoff(env:Env,d:DeviceRow){
 if(!d.owner_id||d.revoked_at)throw permissionDenied('设备尚未授权或已撤销');
 const held=await env.DB.prepare(`SELECT * FROM agent_bridge_handoffs WHERE device_id=?1 AND state IN ('claimed','running','waiting_input','uploading','cancel_requested','dispatch_uncertain') LIMIT 1`).bind(d.id).first<HandoffRow>();if(held){await requireBridgeDeviceScope(env,d,held.project_id);return bridgeDto(await refreshBridgeHandoff(env,held));}
 const rows=(await env.DB.prepare("SELECT * FROM agent_bridge_handoffs WHERE device_id=?1 AND state IN ('checking','waiting_device') ORDER BY created_at,id LIMIT 20").bind(d.id).all<HandoffRow>()).results;
 for(const candidate of rows){await requireBridgeDeviceScope(env,d,candidate.project_id);await bridgeMember(env,candidate.project_id,candidate.requested_by);const r=await refreshBridgeHandoff(env,candidate);if(r.state!=='waiting_device')continue;const e=await readTaskAgentEligibility(env,r.project_id,r.task_id,r.requested_by);if(e.status!=='ready'||!e.eligible||e.sourceHash!==r.eligibility_hash){await env.DB.prepare("UPDATE agent_bridge_handoffs SET state='blocked',reason='AI 判断或配置已失效' WHERE id=?1 AND state='waiting_device'").bind(r.id).run();continue;}
 const claimed=await env.DB.prepare(`UPDATE agent_bridge_handoffs SET state='claimed',updated_at=?2 WHERE id=?1 AND state='waiting_device' AND expires_at>?2 AND stale=0 AND context_stamp=(SELECT ${bridgeContextStampSql} FROM tasks t WHERE t.id=agent_bridge_handoffs.task_id AND t.project_id=agent_bridge_handoffs.project_id AND t.archived_at IS NULL)
 AND EXISTS(SELECT 1 FROM agent_bridge_devices d JOIN agent_bridge_scopes s ON s.device_id=d.id JOIN project_members m ON m.project_id=s.project_id AND m.user_id=d.owner_id JOIN projects p ON p.id=s.project_id WHERE d.id=agent_bridge_handoffs.device_id AND d.revoked_at IS NULL AND s.project_id=agent_bridge_handoffs.project_id AND s.workspace_label IS NOT NULL AND p.status='active' AND p.ai_collaboration_enabled=1)
 AND EXISTS(SELECT 1 FROM task_agent_eligibility s JOIN jobs j ON j.id=s.job_id JOIN ai_config_versions cfg ON cfg.id=json_extract(j.input_json,'$.configVersionId') WHERE s.task_id=agent_bridge_handoffs.task_id AND s.project_id=agent_bridge_handoffs.project_id AND s.source_hash=agent_bridge_handoffs.eligibility_hash AND s.status='ready' AND s.eligible=1 AND cfg.enabled=1 AND cfg.version=(SELECT MAX(version) FROM ai_config_versions))
 AND NOT EXISTS(SELECT 1 FROM agent_bridge_handoffs h WHERE h.device_id=agent_bridge_handoffs.device_id AND h.id!=agent_bridge_handoffs.id AND h.state IN ('claimed','running','waiting_input','uploading','cancel_requested','dispatch_uncertain'))`).bind(r.id,nowIso()).run();if(claimed.meta.changes)return bridgeDto(await loadBridgeHandoff(env,r.id));}
 const concurrent=await env.DB.prepare("SELECT * FROM agent_bridge_handoffs WHERE device_id=?1 AND state IN ('claimed','running','waiting_input','uploading','cancel_requested','dispatch_uncertain') LIMIT 1").bind(d.id).first<HandoffRow>();return concurrent?bridgeDto(concurrent):null;
}
export async function bridgeSnapshot(env:Env,r:HandoffRow):Promise<BridgeSnapshot>{if(!r.snapshot_key||!r.snapshot_hash||!active.includes(r.state))throw invalidState('任务尚未受理');const object=await env.FILES.get(r.snapshot_key);if(!object)throw notFound('交接快照缺失');return object.json<BridgeSnapshot>();}
export async function bridgeInput(env:Env,r:HandoffRow,fileId:string){const snapshot=await bridgeSnapshot(env,r),f=snapshot.files.find(f=>f.fileId===fileId);if(!f)throw permissionDenied('文件不在此交接输入清单');const valid=await env.DB.prepare("SELECT 1 FROM files WHERE id=?1 AND project_id=?2 AND status='available' AND deleted_at IS NULL AND lifecycle_version=?3 AND sha256 IS ?4").bind(fileId,r.project_id,f.lifecycleVersion,f.sha256).first();if(!valid)throw invalidState('输入文件生命周期已变化');return readFileContent(env,{projectId:r.project_id,fileId});}
export type BridgeEvent={sequence:number;type:'session_created'|'prompt_accepted'|'running'|'waiting_input'|'uploading'|'failed'|'cancelled'|'dispatch_uncertain';sessionId?:string;message?:string};
/** Revoked capabilities can acknowledge only their own run's terminal cancellation. */
export async function acknowledgeBridgeCancellation(env:Env,id:string,d:DeviceRow,event:BridgeEvent){
 const r=await loadBridgeHandoff(env,id);if(event.type!=='cancelled'||!d.owner_id||r.device_id!==d.id||r.requested_by!==d.owner_id)throw permissionDenied('取消确认不属于此设备');
 if(r.session_id&&event.sessionId!==r.session_id)throw permissionDenied('取消确认会话不匹配');
 const payload=JSON.stringify(event),old=await env.DB.prepare('SELECT payload_json FROM agent_bridge_events WHERE handoff_id=?1 AND sequence=?2').bind(r.id,event.sequence).first<{payload_json:string}>();if(old&&old.payload_json!==payload)throw invalidState('相同事件序号的内容不同');
 const ack={acknowledged:true as const,state:'cancelled' as const};
 if(r.state==='cancelled')return ack;if(!active.includes(r.state)||event.sequence<=r.last_sequence)throw invalidState('交接状态或取消确认序号不匹配');
 const allowed=await env.DB.prepare(`SELECT 1 FROM agent_bridge_handoffs h WHERE h.id=?1 AND (h.state='cancel_requested' OR NOT (${bridgeAuthoritySql('h')}))`).bind(r.id).first();if(!allowed)throw invalidState('交接未请求取消且设备授权仍有效');
 const results=await env.DB.batch([
  env.DB.prepare(`INSERT INTO agent_bridge_events(handoff_id,sequence,payload_json,created_at) SELECT ?1,?2,?3,?4 WHERE EXISTS(SELECT 1 FROM agent_bridge_handoffs h JOIN agent_bridge_devices d ON d.id=h.device_id WHERE h.id=?1 AND h.device_id=?5 AND h.requested_by=?6 AND d.owner_id=?6 AND h.last_sequence=?7 AND h.state IN ('claimed','running','waiting_input','uploading','cancel_requested','dispatch_uncertain') AND (h.session_id IS NULL OR h.session_id=?8) AND (h.state='cancel_requested' OR NOT (${bridgeAuthoritySql('h')})))`).bind(r.id,event.sequence,payload,nowIso(),d.id,d.owner_id,r.last_sequence,event.sessionId??null),
  env.DB.prepare(`UPDATE agent_bridge_handoffs SET state='cancelled',last_sequence=?2,updated_at=?3 WHERE id=?1 AND last_sequence=?4 AND EXISTS(SELECT 1 FROM agent_bridge_events WHERE handoff_id=?1 AND sequence=?2 AND payload_json=?5)`).bind(r.id,event.sequence,nowIso(),r.last_sequence,payload),
 ]);
 if(!results[0]!.meta.changes&&(await loadBridgeHandoff(env,r.id)).state!=='cancelled')throw invalidState('取消确认状态已变化');return ack;
}
export async function recordBridgeEvent(env:Env,r:HandoffRow,event:BridgeEvent){
 const payload=JSON.stringify(event),old=await env.DB.prepare('SELECT payload_json FROM agent_bridge_events WHERE handoff_id=?1 AND sequence=?2').bind(r.id,event.sequence).first<{payload_json:string}>();if(old){if(old.payload_json!==payload)throw invalidState('相同事件序号的内容不同');return bridgeDto(await loadBridgeHandoff(env,r.id));}
 if(event.sequence<=r.last_sequence)throw invalidState('事件序号落后');if(r.session_id&&event.sessionId&&r.session_id!==event.sessionId)throw invalidState('同一交接不能更换 DSH 会话');
 if(!active.includes(r.state))throw invalidState('交接已结束或尚未受理');
 if(r.state==='dispatch_uncertain'&&!['cancelled','failed','dispatch_uncertain'].includes(event.type))throw invalidState('不明确的派发不能自动恢复执行');
 if(event.type==='session_created'&&(r.state!=='claimed'||!event.sessionId))throw invalidState('仅受理阶段可登记会话，且必须提供会话标识');
 if(['prompt_accepted','running','waiting_input','uploading'].includes(event.type)&&!r.session_id&&!event.sessionId)throw validationFailed('执行状态需要会话标识');
 const state:BridgeState=event.type==='session_created'?'claimed':event.type==='prompt_accepted'?'running':event.type;
 const results=await env.DB.batch([env.DB.prepare(`INSERT INTO agent_bridge_events(handoff_id,sequence,payload_json,created_at) SELECT ?1,?2,?3,?4 WHERE EXISTS(SELECT 1 FROM agent_bridge_handoffs h WHERE id=?1 AND last_sequence=?5 AND state=?6 AND ${bridgeAuthoritySql('h')})`).bind(r.id,event.sequence,payload,nowIso(),r.last_sequence,r.state),env.DB.prepare(`UPDATE agent_bridge_handoffs SET state=CASE WHEN state='cancel_requested' AND ?3 NOT IN ('cancelled','failed','dispatch_uncertain') THEN state ELSE ?3 END,session_id=COALESCE(session_id,?4),reason=?5,last_sequence=?2,updated_at=?6 WHERE id=?1 AND last_sequence=?7 AND ${bridgeAuthoritySql()} AND EXISTS(SELECT 1 FROM agent_bridge_events WHERE handoff_id=?1 AND sequence=?2 AND payload_json=?8)`).bind(r.id,event.sequence,state,event.sessionId??null,event.message??null,nowIso(),r.last_sequence,payload)]);
 if(!results[0]!.meta.changes){const saved=await env.DB.prepare('SELECT payload_json FROM agent_bridge_events WHERE handoff_id=?1 AND sequence=?2').bind(r.id,event.sequence).first<{payload_json:string}>();if(saved?.payload_json!==payload)throw invalidState('状态已变化，请重新读取');}
 return bridgeDto(await loadBridgeHandoff(env,r.id));
}
export async function cancelBridgeHandoff(env:Env,r:HandoffRow){if(['checking','waiting_device'].includes(r.state))await env.DB.prepare("UPDATE agent_bridge_handoffs SET state='cancelled',updated_at=?2 WHERE id=?1 AND state IN ('checking','waiting_device')").bind(r.id,nowIso()).run();else if(active.includes(r.state))await env.DB.prepare("UPDATE agent_bridge_handoffs SET state='cancel_requested',updated_at=?2 WHERE id=?1 AND state IN ('claimed','running','waiting_input','uploading','dispatch_uncertain')").bind(r.id,nowIso()).run();return bridgeDto(await loadBridgeHandoff(env,r.id));}
type ArtifactRow={artifact_id:string;file_id:string;name:string;size_bytes:number;sha256:string;stored:number};
export async function bridgeArtifactInit(env:Env,r:HandoffRow,input:{artifactId:string;name:string;sizeBytes:number;sha256:string;contentType?:string}){
 if(!executing.includes(r.state))throw invalidState('当前交接不能上传成果');if(/[\\/\u0000-\u001f]/.test(input.name)||input.name==='.'||input.name==='..')throw validationFailed('成果名称必须是文件名');const limit=uploadLimit(extOf(input.name));if(input.sizeBytes>(limit??50*1024*1024))throw fileTooLarge(limit??50*1024*1024);
 let a=await env.DB.prepare('SELECT * FROM agent_bridge_artifacts WHERE handoff_id=?1 AND artifact_id=?2').bind(r.id,input.artifactId).first<ArtifactRow>();
 if(a){if(a.name!==input.name||a.size_bytes!==input.sizeBytes||a.sha256!==input.sha256)throw invalidState('相同成果标识的清单不同');}
 else{if((await env.DB.prepare('SELECT COUNT(*) n FROM agent_bridge_artifacts WHERE handoff_id=?1').bind(r.id).first<{n:number}>())!.n>=20)throw validationFailed('单次交接最多20份成果');const f=await createFileInit(env,{projectId:r.project_id,uploaderUserId:r.requested_by,fileName:input.name,contentType:input.contentType});await env.DB.prepare('INSERT OR IGNORE INTO agent_bridge_artifacts(handoff_id,artifact_id,file_id,name,size_bytes,sha256) VALUES(?1,?2,?3,?4,?5,?6)').bind(r.id,input.artifactId,f.fileId,input.name,input.sizeBytes,input.sha256).run();a=(await env.DB.prepare('SELECT * FROM agent_bridge_artifacts WHERE handoff_id=?1 AND artifact_id=?2').bind(r.id,input.artifactId).first<ArtifactRow>())!;}
 return{artifactId:a.artifact_id,fileId:a.file_id,uploadPath:`/api/v1/agent-bridges/handoffs/${r.id}/artifacts/${a.artifact_id}/content`,stored:!!a.stored};
}
export async function storeBridgeArtifact(env:Env,r:HandoffRow,artifactId:string,bytes:Uint8Array){
 if(!executing.includes(r.state))throw invalidState('当前交接不能上传成果');const a=await env.DB.prepare('SELECT * FROM agent_bridge_artifacts WHERE handoff_id=?1 AND artifact_id=?2').bind(r.id,artifactId).first<ArtifactRow>();if(!a)throw notFound();if(bytes.length!==a.size_bytes||await sha256Hex(bytes)!==a.sha256)throw validationFailed('成果字节数或 SHA256 与清单不匹配');
 const existing=await env.DB.prepare("SELECT size_bytes,sha256 FROM files WHERE id=?1 AND project_id=?2 AND status='available' AND deleted_at IS NULL").bind(a.file_id,r.project_id).first<{size_bytes:number;sha256:string}>();if(existing){if(existing.size_bytes!==a.size_bytes||existing.sha256!==a.sha256)throw invalidState('已存储的成果与清单不同');}else await storeFileContent(env,{projectId:r.project_id,fileId:a.file_id,bytes});
 const stored=await env.DB.prepare(`UPDATE agent_bridge_artifacts SET stored=1 WHERE handoff_id=?1 AND artifact_id=?2 AND EXISTS(SELECT 1 FROM agent_bridge_handoffs h WHERE h.id=?1 AND h.state IN ('claimed','running','waiting_input','uploading') AND ${bridgeAuthoritySql('h')})`).bind(r.id,artifactId).run();if(!stored.meta.changes)throw permissionDenied('交接或设备授权已变化');return{stored:true,fileId:a.file_id};
}
export async function completeBridgeHandoff(env:Env,r:HandoffRow,input:{summary:string;artifactIds:string[];sessionId:string}){
 if(r.session_id!==input.sessionId)throw invalidState('成果会话标识不匹配');if(new Set(input.artifactIds).size!==input.artifactIds.length)throw validationFailed('成果不可重复');
 const artifacts=(await env.DB.prepare(`SELECT a.* FROM agent_bridge_artifacts a JOIN files f ON f.id=a.file_id AND f.project_id=?2 WHERE a.handoff_id=?1 AND a.artifact_id IN(SELECT value FROM json_each(?3)) AND a.stored=1 AND f.status='available' AND f.deleted_at IS NULL AND f.size_bytes=a.size_bytes AND f.sha256=a.sha256 ORDER BY a.artifact_id`).bind(r.id,r.project_id,JSON.stringify(input.artifactIds)).all<ArtifactRow>()).results;if(artifacts.length!==input.artifactIds.length)throw invalidState('成果文件尚未完整上传或已不可用');
 const result:BridgeResult={summary:input.summary,artifacts:artifacts.map(a=>({artifactId:a.artifact_id,fileId:a.file_id,name:a.name,sizeBytes:a.size_bytes,sha256:a.sha256}))},json=JSON.stringify(result);
 if(r.state==='ready_for_review'){if(r.result_json!==json)throw invalidState('已完成交接的成果不能替换');return bridgeDto(r);}
 if(!['running','waiting_input','uploading'].includes(r.state))throw invalidState('当前交接不能完成');
 const updated=await env.DB.prepare(`UPDATE agent_bridge_handoffs SET state='ready_for_review',result_json=?2,updated_at=?3 WHERE id=?1 AND state IN ('running','waiting_input','uploading') AND session_id=?4 AND ${bridgeAuthoritySql()} AND NOT EXISTS(SELECT 1 FROM json_each(?5) j WHERE NOT EXISTS(SELECT 1 FROM agent_bridge_artifacts a JOIN files f ON f.id=a.file_id WHERE a.handoff_id=?1 AND a.artifact_id=j.value AND a.stored=1 AND f.status='available' AND f.deleted_at IS NULL AND f.size_bytes=a.size_bytes AND f.sha256=a.sha256))`).bind(r.id,json,nowIso(),input.sessionId,JSON.stringify(input.artifactIds)).run();if(!updated.meta.changes)throw invalidState('交接已取消或成果已变化');return bridgeDto(await refreshBridgeHandoff(env,await loadBridgeHandoff(env,r.id)));
}
