import type { Env } from '../env';
import { newId, nowIso } from '../core/db';
import { invalidState, permissionDenied, validationFailed } from '../core/errors';
import { audit, toSubmission, type CollaborationTask, type Submission } from './collaboration';
import { enqueueEvaluation } from './collaboration-evaluation';
import { loadAiConfig } from '../ai/config';

export type SubmissionInput={projectId:string;taskId:string;userId:string;expectedRevision:number;body:string;materialVersionIds:string[]};
/** Shared submission transaction for browser submission and reviewed bridge adoption. */
export function submissionStatements(env:Env,p:SubmissionInput,id:string,now:string,extraGuard='1=1'){
 return [env.DB.prepare(`INSERT INTO task_submissions(id,project_id,task_id,round,submitted_by,body,material_versions_json,criteria,task_revision,created_at,updated_at) SELECT ?1,?2,id,1+COALESCE((SELECT MAX(round) FROM task_submissions WHERE task_id=?3),0),?4,?5,?6,criteria,revision+1,?7,?7 FROM tasks WHERE id=?3 AND project_id=?2 AND assignee_id=?4 AND revision=?8 AND archived_at IS NULL AND criteria!='' AND (lifecycle_state IN ('in_progress','improve','rework') OR (lifecycle_state IS NULL AND status!='done')) AND EXISTS(SELECT 1 FROM project_members WHERE project_id=?2 AND user_id=?4) AND NOT EXISTS(SELECT 1 FROM json_each(?6) j WHERE NOT EXISTS(SELECT 1 FROM material_versions v JOIN materials m ON m.id=v.material_id WHERE v.id=j.value AND m.project_id=?2)) AND (SELECT COUNT(*) FROM task_submissions WHERE task_id=?3)<20 AND ${extraGuard}`).bind(id,p.projectId,p.taskId,p.userId,p.body,JSON.stringify(p.materialVersionIds),now,p.expectedRevision),
 env.DB.prepare(`UPDATE tasks SET lifecycle_state='submitted',status='doing',current_submission_id=?1,revision=revision+1,updated_at=?2 WHERE id=?3 AND EXISTS(SELECT 1 FROM task_submissions WHERE id=?1)`).bind(id,now,p.taskId),audit(env,p.projectId,p.userId,'collaboration.submitted',id,{taskId:p.taskId},true)];
}
export async function validateSubmission(env:Env,p:SubmissionInput){const t=await env.DB.prepare('SELECT * FROM tasks WHERE id=?1 AND project_id=?2').bind(p.taskId,p.projectId).first<CollaborationTask>();if(!t||t.assignee_id!==p.userId)throw permissionDenied('仅当前任务执行人可提交');if(!t.criteria.trim())throw validationFailed('请先补充任务验收标准再提交');if(new Set(p.materialVersionIds).size!==p.materialVersionIds.length)throw validationFailed('版本不可重复');return t;}
export async function submittedResult(env:Env,projectId:string,id:string,userId:string){let evaluationError:string|undefined;try{const config=await loadAiConfig(env.DB),settings=await env.DB.prepare('SELECT ai_collaboration_enabled FROM projects WHERE id=?1').bind(projectId).first<{ai_collaboration_enabled:number}>();if(config?.enabled&&settings?.ai_collaboration_enabled===1)await enqueueEvaluation(env,projectId,id,userId);}catch(e){evaluationError=e instanceof Error?e.message:'本轮AI评价未能启动，请负责人验收';}const row=await env.DB.prepare('SELECT * FROM task_submissions WHERE id=?1').bind(id).first<Submission>();if(!row)throw invalidState('任务提交未完成');return{...toSubmission(row),...(evaluationError?{evaluationError}:{})};}
export async function submitCollaborationTask(env:Env,p:SubmissionInput){await validateSubmission(env,p);const id=newId(),results=await env.DB.batch(submissionStatements(env,p,id,nowIso()));if(!results[0]!.meta.changes)throw invalidState('任务已变化、材料不属于本项目或已达20轮上限');return submittedResult(env,p.projectId,id,p.userId);}
