import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {ManualAssessmentEditor} from './ManualAssessmentEditor';
import type {StandardVersion,Assessment} from '../api/simplification';
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
const standard={standardsVersionId:'s',rubric:{weights:[{key:'quality',label:'质量',weight:1}]}} as StandardVersion;
it('creates independent human scoring without an AI capability prerequisite',async()=>{const fetch=vi.fn(async()=>Response.json({data:{assessmentId:'a'},requestId:'r'}));vi.stubGlobal('fetch',fetch);const saved=vi.fn(async()=>{});render(<QueryClientProvider client={new QueryClient()}><ManualAssessmentEditor projectId="p" standard={standard} goalRevision={2} materialVersionIds={[]} onSaved={saved}/></QueryClientProvider>);fireEvent.click(screen.getByText('填写分项分数与修正反馈'));fireEvent.change(screen.getByLabelText('质量（0—100）'),{target:{value:'88'}});fireEvent.change(screen.getByLabelText('人工评分或修正理由'),{target:{value:'人工核对'}});fireEvent.click(screen.getByRole('button',{name:'保存人工评分'}));await waitFor(()=>expect(saved).toHaveBeenCalled());const [url,options]=fetch.mock.calls[0] as unknown as [string,RequestInit];expect(url).toBe('/api/v1/projects/p/assessments/manual');expect(JSON.parse(String(options.body))).toMatchObject({scores:[{key:'quality',score:88}],reason:'人工核对'});});
it('only sends edited dimensions and the current revision for a correction',async()=>{const fetch=vi.fn(async()=>Response.json({data:{assessmentId:'a'},requestId:'r'}));vi.stubGlobal('fetch',fetch);render(<QueryClientProvider client={new QueryClient()}><ManualAssessmentEditor projectId="p" standard={standard} assessment={{assessmentId:'a',revision:5,report:{scores:[{key:'quality',score:70,comment:'旧意见'}]}} as Assessment} materialVersionIds={[]} onSaved={async()=>{}}/></QueryClientProvider>);fireEvent.click(screen.getByText('填写分项分数与修正反馈'));fireEvent.change(screen.getByLabelText('质量（0—100）'),{target:{value:''}});fireEvent.change(screen.getByLabelText('人工评分或修正理由'),{target:{value:'证据不足'}});fireEvent.click(screen.getByRole('button',{name:'保存人工评分'}));await waitFor(()=>expect(fetch).toHaveBeenCalled());const [url,options]=fetch.mock.calls[0] as unknown as [string,RequestInit];expect(url).toBe('/api/v1/projects/p/assessments/a/scores');expect(options.method).toBe('PATCH');expect(JSON.parse(String(options.body))).toMatchObject({expectedRevision:5,scores:[{key:'quality',score:null}]});});
