import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { projectRequest, type Assessment, type AssessmentReport, type StandardVersion } from '../api/simplification';
import { idempotencyKeyForIntent, completeIntent } from './aiWorkflowSupport';
import { ErrorNotice, Field, SectionCard } from '../components/ui';
export function ManualAssessmentEditor({projectId,standard,assessment,goalRevision,materialVersionIds,onSaved}:{projectId:string;standard?:StandardVersion;assessment?:Assessment;goalRevision?:number;materialVersionIds:string[];onSaved:(result:Assessment)=>Promise<void>}) {
 const obsolete=Boolean(assessment && assessment.standardsVersionId !== standard?.standardsVersionId);
 const report=assessment?.report as AssessmentReport | undefined;
 const [values,setValues]=useState<Record<string,string>>({}); const [comments,setComments]=useState<Record<string,string>>({}); const [reason,setReason]=useState(''); const [summary,setSummary]=useState(report?.summary ?? '');
 const save=useMutation({mutationFn:async()=>{if(!standard)throw new Error('请先保存项目标准。');if(obsolete)throw new Error('项目标准已更新，请新建评分。');const scores=standard.rubric.weights.filter(dim=>!assessment || dim.key in values || dim.key in comments).map(dim=>({key:dim.key,score:(values[dim.key] ?? String(report?.scores?.find(row=>row.key===dim.key)?.score ?? '')).trim()===''?null:Number(values[dim.key] ?? report?.scores?.find(row=>row.key===dim.key)?.score),comment:comments[dim.key] ?? report?.scores?.find(row=>row.key===dim.key)?.comment ?? ''})); if(!scores.length)throw new Error('请修改至少一个维度。');const body=assessment?{expectedRevision:assessment.revision,scores,reason,summary}:{materialVersionIds,goalRevision,scores,reason,summary}; const namespace='manual-assessment:'+projectId+':'+(assessment?.assessmentId ?? 'create'); const key=await idempotencyKeyForIntent(namespace,body); const result=await projectRequest<Assessment>(projectId,assessment?'/assessments/'+encodeURIComponent(assessment.assessmentId)+'/scores':'/assessments/manual',{method:assessment?'PATCH':'POST',body,idempotencyKey:key}); completeIntent(namespace); return result;},onSuccess:onSaved});
 return <SectionCard title={assessment?'修正本轮评分':'独立人工评分'} detail="人工操作不受 AI 开关或自动审核方式限制。空分数表示未评分，原始 AI 建议保留。"><details><summary>填写分项分数与修正反馈</summary><p>{obsolete ? '项目标准已更新，本轮仅供查看；请按生效标准新建评分。' : standard ? `生效标准：${standard.title} · v${standard.version}` : '尚未保存项目标准'}</p><form className="stack" onSubmit={event=>{event.preventDefault();save.mutate();}}>{standard?.rubric.weights.map(dim=><div className="form-grid-two" key={dim.key}><Field label={dim.label+'（0—100）'}><input className="input" type="number" min="0" max="100" step="0.1" value={values[dim.key] ?? String(report?.scores?.find(row=>row.key===dim.key)?.score ?? '')} onChange={event=>setValues({...values,[dim.key]:event.target.value})}/></Field><Field label={dim.label+'评语'}><textarea className="input" value={comments[dim.key] ?? report?.scores?.find(row=>row.key===dim.key)?.comment ?? ''} onChange={event=>setComments({...comments,[dim.key]:event.target.value})}/></Field></div>)}<Field label="总体反馈"><textarea className="input" value={summary} onChange={event=>setSummary(event.target.value)}/></Field><Field label="人工评分或修正理由"><textarea className="input" required maxLength={4000} value={reason} onChange={event=>setReason(event.target.value)}/></Field>{save.error&&<ErrorNotice error={save.error}/>}<button className="button button-primary" disabled={obsolete || !standard || !reason.trim() || save.isPending}>{save.isPending?'保存中…':'保存人工评分'}</button></form></details></SectionCard>;
}
