import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { projectRequest } from '../api/simplification';
import { type CollaborationProposal } from '../api/collaboration';
import { ErrorNotice, Field } from '../components/ui';
type Row = Record<string, unknown>;
export function ProposalCorrection({projectId,proposal,members,onChanged}:{projectId:string;proposal:CollaborationProposal;members:{userId:string;displayName:string}[];onChanged:()=>Promise<void>}) {
 const [payload,setPayload]=useState<Record<string, unknown>>(proposal.payload); const [reason,setReason]=useState(''); const [excluded,setExcluded]=useState<string[]>([]);
 const rows=(key:string):Row[]=>Array.isArray(payload[key])?payload[key] as Row[]:[];
 const update=(key:string,index:number,field:string,value:unknown)=>setPayload({...payload,[key]:rows(key).map((row,i)=>i===index?{...row,[field]:value}:row)});
 const revise=useMutation({mutationFn:()=>projectRequest(projectId,'/collaboration/proposals/'+encodeURIComponent(proposal.proposalId),{method:'PATCH',body:{expectedRevision:proposal.revision,payload,reason}}),onSuccess:onChanged});
 const apply=useMutation({mutationFn:()=>projectRequest(projectId,'/collaboration/proposals/'+encodeURIComponent(proposal.proposalId)+'/apply',{method:'POST',body:{expectedRevision:proposal.revision,selectedTaskKeys:rows('tasks').filter(row=>!excluded.includes('tasks:'+row.key)).map(row=>row.key),selectedUpdateTaskIds:rows('updates').filter(row=>!excluded.includes('updates:'+row.taskId)).map(row=>row.taskId),selectedAssignmentTaskIds:rows('assignments').filter(row=>!excluded.includes('assignments:'+row.taskId)).map(row=>row.taskId)}}),onSuccess:onChanged});
 const feedback=useMutation({mutationFn:()=>projectRequest(projectId,'/collaboration/feedback',{method:'POST',body:{targetType:'proposal',targetId:proposal.proposalId,feedback:reason,requestAiRedo:true}}),onSuccess:onChanged});
 return <details><summary>修正建议、部分应用或重新反馈</summary><div className="stack"><p className="form-note">先保存修改，再按最新版本应用。已应用方案请通过任务详情修正；反馈会进入后续 AI 判断。</p>{proposal.status==='pending'&&(['tasks','updates','assignments'] as const).map(key=>rows(key).map((row,index)=>{const id=key+':'+(row.key??row.taskId);return <fieldset key={id}><legend><label><input type="checkbox" checked={!excluded.includes(id)} onChange={event=>setExcluded(current=>event.target.checked?current.filter(item=>item!==id):[...current,id])}/>应用此条目</label></legend>{key==='assignments'?<Field label="执行人"><select className="input" value={String(row.assigneeId??'')} onChange={event=>update(key,index,'assigneeId',event.target.value||null)}><option value="">暂不分配</option>{members.map(member=><option key={member.userId} value={member.userId}>{member.displayName}</option>)}</select></Field>:<>{(['title','detail','criteria'] as const).map(field=><Field label={{title:'任务名称',detail:'说明',criteria:'验收标准'}[field]} key={field}><textarea className="input" value={String(row[field]??'')} onChange={event=>update(key,index,field,event.target.value)}/></Field>)}<Field label="预计工时"><input className="input" type="number" min="0.25" max="200" step="0.25" value={Number(row.effortHours??1)} onChange={event=>update(key,index,'effortHours',Number(event.target.value))}/></Field>{key==='tasks'&&<Field label="前置任务标识（逗号分隔）"><input className="input" value={Array.isArray(row.dependsOn)?row.dependsOn.join(','):''} onChange={event=>update(key,index,'dependsOn',event.target.value.split(',').map(item=>item.trim()).filter(Boolean))}/></Field>}</>}</fieldset>;}))}<Field label="修正理由或重新反馈"><textarea className="input" maxLength={4000} value={reason} onChange={event=>setReason(event.target.value)}/></Field><div className="form-actions">{proposal.status==='pending'&&<><button className="button" disabled={!reason.trim()||revise.isPending} onClick={()=>revise.mutate()}>保存方案修正</button><button className="button" disabled={apply.isPending} onClick={()=>apply.mutate()}>应用选中条目</button></>}<button className="button" disabled={!reason.trim()||feedback.isPending} onClick={()=>feedback.mutate()}>反馈并要求 AI 重新判断</button></div>{[revise.error,apply.error,feedback.error].filter(Boolean).map((error,i)=><ErrorNotice key={i} error={error}/>)}</div></details>;
}
